import type { CliRoutedOperation } from "./operations";

const REQUEST_ID = "11111111-1111-4111-8111-111111111111";

/** Live BB catalog id for the agency skill. MCP discovery is unavailable — keep mcpIds empty. */
export const EXAMPLE_CATALOG_SKILL_ID =
  "skill_6153a163fb7fac8c435f3befc88db8417cd0722ba8fdf5ecc37b2b5069ffc3ff";

/** Полные валидируемые примеры. Policy — содержимое, не label. */
export const CLI_EXAMPLES: Record<CliRoutedOperation, unknown> = {
  listWorkspace: { bindingId: "binding_aaaaaaaa", claimedBbProjectId: "proj_trusted" },
  listBbCatalog: {},
  listCapabilityCatalog: { bindingId: "binding_aaaaaaaa" },
  getJob: { jobId: "job_aaaaaaaaaaaa", key: "AG-101" },
  getAgent: { agentId: "agent_aaaaaaaa" },
  getDepartment: { departmentId: "departme_aaaaaaaa" },
  listArtifactVersions: { artifactId: "artifact_aaaaaaaa", jobId: "job_aaaaaaaaaaaa" },
  createPolicyVersion: {
    requestId: REQUEST_ID,
    allowedCapabilities: ["read.files"],
    cliHostConstraints: { providerIds: ["codex"], hostIds: ["host_mini"] },
    secretRefs: ["OPENAI_API_KEY"],
  },
  provisionAgent: {
    requestId: REQUEST_ID,
    name: "Редактор",
    state: "active",
    version: {
      version: 1,
      role: "editor",
      instructions: "Править тексты по брифу.",
      providerId: "codex",
      model: "gpt-5.6",
      skillIds: [EXAMPLE_CATALOG_SKILL_ID],
      mcpIds: [],
      policyVersionId: "policy_aaaaaaaa",
    },
  },
  saveAgentProfile: {
    requestId: REQUEST_ID,
    expectedRevision: 1,
    agentId: "agent_aaaaaaaa",
    name: "Редактор",
    state: "active",
    version: {
      version: 2,
      role: "editor",
      instructions: "Править тексты по брифу.",
      providerId: "codex",
      model: "gpt-5.6",
      skillIds: [EXAMPLE_CATALOG_SKILL_ID],
      mcpIds: [],
      policyVersionId: "policy_aaaaaaaa",
    },
  },
  provisionDepartment: {
    requestId: REQUEST_ID,
    name: "Редактура",
    leadAgentId: "agent_aaaaaaaa",
    process: {
      instructions: "Черновик, затем проверка.",
      acceptance: "Есть принятая версия файла.",
      reviewPolicy: { required: true },
    },
  },
  saveDepartmentProfile: {
    requestId: REQUEST_ID,
    expectedRevision: 1,
    departmentId: "departme_aaaaaaaa",
    name: "Редактура",
    leadAgentId: "agent_aaaaaaaa",
    process: {
      instructions: "Черновик, затем проверка.",
      acceptance: "Есть принятая версия файла.",
      reviewPolicy: { required: true },
    },
    memberships: [{ agentId: "agent_aaaaaaaa", role: "lead" }],
  },
  addMembership: {
    requestId: REQUEST_ID,
    departmentId: "departme_aaaaaaaa",
    agentId: "agent_bbbbbbbb",
    role: "member",
  },
  removeMembership: {
    requestId: REQUEST_ID,
    departmentId: "departme_aaaaaaaa",
    agentId: "agent_bbbbbbbb",
  },
  createProjectBinding: {
    requestId: REQUEST_ID,
    bbProjectId: "proj_trusted",
    environmentId: "env_local01",
    hostId: "host_mini",
    canonicalRoot: "/Users/vechkasov/Documents/SelfyStudio",
    policyVersionId: "policy_aaaaaaaa",
    sectionId: null,
  },
  linkDepartment: {
    requestId: REQUEST_ID,
    bindingId: "binding_aaaaaaaa",
    departmentId: "departme_aaaaaaaa",
  },
  createJob: {
    requestId: REQUEST_ID,
    key: "AG-101",
    bindingId: "binding_aaaaaaaa",
    departmentId: "departme_aaaaaaaa",
    title: "Карточка",
    brief: "Собрать.",
    acceptance: "Текст принят.",
    parentJobId: null,
    assignedAgentId: "agent_aaaaaaaa",
    priority: "normal",
    dueAt: null,
  },
  updateJob: {
    requestId: REQUEST_ID,
    expectedRevision: 1,
    jobId: "job_aaaaaaaaaaaa",
    assignedAgentId: "agent_aaaaaaaa",
  },
  transitionJob: {
    requestId: REQUEST_ID,
    expectedRevision: 1,
    jobId: "job_aaaaaaaaaaaa",
    to: "queued",
  },
  createArtifact: {
    requestId: REQUEST_ID,
    jobId: "job_aaaaaaaaaaaa",
  },
  publishArtifactVersion: {
    requestId: REQUEST_ID,
    artifactId: "artifact_aaaaaaaa",
    jobId: "job_aaaaaaaaaaaa",
    relativePath: "docs/note.md",
    mime: "text/markdown",
    size: 4,
    hash: "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
    bytesBase64: "MTIzNA==",
  },
  reportNeedsInput: {
    requestId: REQUEST_ID,
    expectedRevision: 1,
    jobId: "job_aaaaaaaaaaaa",
    expectedAttemptRevision: 1,
    attemptId: "runattempt_aaaaaaaa",
    launchId: REQUEST_ID,
    threadId: "thr_ag1604wait01",
    questions: [
      {
        id: "q1",
        text: "Какой acceptance выполнять при противоречии?",
        sourceRefs: [
          { kind: "process_acceptance", id: "prc_00000001" },
          { kind: "job_acceptance", id: "job_aaaaaaaaaaaa" },
        ],
      },
    ],
  },
  answerNeedsInput: {
    requestId: REQUEST_ID,
    expectedRevision: 2,
    jobId: "job_aaaaaaaaaaaa",
    expectedAttemptRevision: 2,
    attemptId: "runattempt_aaaaaaaa",
    launchId: REQUEST_ID,
    threadId: "thr_ag1604wait01",
    waitId: REQUEST_ID,
    answers: [{ questionId: "q1", text: "Выполнять Job.acceptance; процесс уточнён." }],
    expectedProcessVersionId: "prc_00000001",
    expectedSnapshotDigest: "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
    expectedProcessInstructionsHash: "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
    expectedProcessAcceptanceHash: "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
    expectedJobBriefHash: "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
    expectedJobAcceptanceHash: "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
  },
  attachJobInput: {
    requestId: REQUEST_ID,
    expectedRevision: 1,
    targetJobId: "job_bbbbbbbbbbbb",
    sourceJobId: "job_aaaaaaaaaaaa",
    artifactId: "artifact_aaaaaaaa",
    version: 1,
    hash: "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
  },
  acceptArtifactVersion: {
    requestId: REQUEST_ID,
    expectedRevision: 1,
    jobId: "job_aaaaaaaaaaaa",
    artifactId: "artifact_aaaaaaaa",
    version: 1,
    hash: "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
  },
  openArtifact: {
    artifactId: "artifact_aaaaaaaa",
    jobId: "job_aaaaaaaaaaaa",
    version: 1,
  },
  prepareLaunch: {
    requestId: REQUEST_ID,
    jobId: "job_aaaaaaaaaaaa",
    expectedRevision: 1,
  },
  getLaunch: {
    launchId: REQUEST_ID,
  },
  reconcileLaunch: {
    requestId: REQUEST_ID,
    attemptId: "runattempt_aaaaaaaa",
    launchId: REQUEST_ID,
  },
  interpretWorkerCompletion: {
    jobId: "job_aaaaaaaaaaaa",
    launchId: REQUEST_ID,
  },
  listJobAttempts: {
    jobId: "job_aaaaaaaaaaaa",
  },
  getIsolationReadiness: {},
  cancelLaunch: {
    requestId: REQUEST_ID,
    jobId: "job_aaaaaaaaaaaa",
    attemptId: "run_aaaaaaaaaaaaaa",
    expectedJobRevision: 1,
    expectedAttemptRevision: 1,
    launchId: REQUEST_ID,
    threadId: "thr_aaaaaaaaaaaa",
    reason: "wrong provider bind; recover same job",
  },
  saveEventDefinition: {
    requestId: REQUEST_ID,
    topic: "research.delivered",
    schemaVersion: 1,
    namespace: "agency",
    label: "Исследование доставлено",
    payloadSchema: { type: "object" },
  },
  saveEventSource: {
    requestId: REQUEST_ID,
    projectId: "proj_trusted",
    kind: "notify",
    enabled: true,
  },
  saveRuleVersion: {
    requestId: REQUEST_ID,
    ruleId: "rule_research01",
    projectId: "proj_trusted",
    topic: "research.delivered",
    conditions: [{ field: "data.status", op: "equals", value: "ready" }],
    mode: "observe",
    action: { kind: "observe" },
    maxDepth: 12,
    maxRetries: 3,
    enabled: true,
  },
  ingestInboxEvent: {
    requestId: REQUEST_ID,
    sourceId: "evs_aaaaaaaa",
    eventId: "delivery-1",
    topic: "research.delivered",
    reference: "artifact:research-1",
    body: { data: { status: "ready" } },
    depth: 0,
  },
  dispatchTick: {
    requestId: REQUEST_ID,
    live: false,
    limit: 20,
  },
  listEventDefinitions: {},
  listEventSources: {},
  listRuleVersions: {},
  listActionIntents: {},
  claimActionIntent: {
    requestId: REQUEST_ID,
    intentId: "ain_aaaaaaaa",
    live: false,
    leaseOwner: "dispatcher-test",
    leaseMs: 60000,
  },
  approveActionIntent: {
    requestId: REQUEST_ID,
    expectedRevision: 1,
    intentId: "ain_aaaaaaaa",
  },
  completeActionIntent: {
    requestId: REQUEST_ID,
    intentId: "ain_aaaaaaaa",
    fencingToken: REQUEST_ID,
    fencingGeneration: 1,
    outcome: "succeeded",
  },
  createJobComment: {
    requestId: REQUEST_ID,
    jobId: "job_aaaaaaaaaaaa",
    comment: "Сверстала оффер v2; проверка на фикстуре прошла. Жду ревью условий.",
    references: [{ type: "thread", id: "thr_exactattempt01" }],
  },
};

export const SKILL_SCHEMA_NOTES = [
  "skillIds — ID из bb agency catalog / listCapabilityCatalog, формат skill_ + 64 hex.",
  "Не подставляй вымышленные skl_* и не бери имя навыка вместо ID.",
  "mcpDiscovery сейчас unavailable: mcpIds оставляй пустым массивом.",
];

export const POLICY_SCHEMA_NOTES = [
  "PolicyVersion неизменяема: новая версия — новый createPolicyVersion, не правка старой.",
  "Права задаёт полный payload: allowedCapabilities, cliHostConstraints, secretRefs.",
  "Не выводить права из catalog label и не считать подпись политики синонимом allowedCapabilities.",
  "Одинаковые политики переиспользуй по полному содержимому из listWorkspace.policies, не по label.",
  "requestId — UUID; save/update требуют expectedRevision из последней записи.",
];
