import { verificationAdviceInputSchema } from "../../shared/contracts/verification-advice";
import { workerContextQuerySchema, saveWorkerContextSchema } from "../../shared/contracts/worker-context";
import { recordLessonFeedbackSchema, leadStateQuerySchema, recordLeadDecisionSchema, submitJobResultSchema } from "../../shared/contracts/lead-control";
import { traceQuerySchema } from "../../shared/contracts/trace";
import { jobDiagnosticsQuerySchema } from "../../shared/contracts/diagnostics";
import { installStarterKitInputSchema, recordLifecycleInputSchema } from "../../shared/rpc-contract";
import { saveDecisionSettingsInputSchema, addJobDependencyRpcSchema, notifyOwnerInputSchema, ownerDigestInputSchema, removeJobDependencyRpcSchema, listKnowledgeInputSchema, saveKnowledgeInputSchema, listIdeasInputSchema, saveIdeaInputSchema, setIdeaStatusInputSchema, spawnIdeaThreadInputSchema, setJobNextStepRpcSchema } from "../../shared/rpc-contract";
import { dequeueLaunchRpcSchema, enqueueLaunchRpcSchema } from "../../shared/rpc-contract";
import { saveAgencyRulesInputSchema, saveTemplateInputSchema } from "../../shared/rpc-contract";
import { savePassportInputSchema, savePassportSettingsInputSchema } from "../../shared/rpc-contract";
import { getWorkRulesInputSchema } from "../../shared/rpc-contract";
import { saveWorkRulesCommandSchema } from "../../shared/contracts/work-rules";
import { getSessionPolicyInputSchema, saveSessionPolicyInputSchema } from "../../shared/contracts/session-policy";
import { listDashboardUsageInputSchema } from "../../shared/contracts/dashboard-usage";
import type { ZodType } from "zod";
import {
  attachJobInputRpcSchema,
  acceptArtifactRpcSchema,
  capabilityCatalogInputSchema,
  createArtifactRpcSchema,
  createJobRpcSchema,
  getAgentInputSchema,
  getDepartmentInputSchema,
  getJobInputSchema,
  linkDepartmentRpcSchema,
  bindingLifecycleRpcSchema,
  readProjectRulesInputSchema,
  saveProjectRulesInputSchema,
  unlinkDepartmentRpcSchema,
  listArtifactVersionsInputSchema,
  listWorkspaceInputSchema,
  openArtifactRpcSchema,
  cancelLaunchCommandSchema,
  returnJobForReworkCommandSchema,
  recoverJobCommandSchema,
  getIsolationReadinessRpcSchema,
  getLaunchRpcSchema,
  interpretWorkerCompletionRpcSchema,
  listJobAttemptsRpcSchema,
  prepareLaunchRpcSchema,
  answerNeedsInputRpcSchema,
  staleAnswerRpcSchema,
  approveActionIntentCommandSchema,
  claimActionIntentCommandSchema,
  completeActionIntentCommandSchema,
  dispatchTickCommandSchema,
  ingestInboxEventCommandSchema,
  listActionIntentsCommandSchema,
  listDispatcherCatalogCommandSchema,
  reportNeedsInputRpcSchema,
  saveEventDefinitionCommandSchema,
  saveEventSourceCommandSchema,
  saveRuleVersionCommandSchema,
  provisionAgentRpcSchema,
  reconcileLaunchRpcSchema,
  provisionDepartmentRpcSchema,
  publishArtifactRpcSchema,
  transitionJobRpcSchema,
  updateJobRpcSchema,
} from "../../shared/rpc-contract";
import { z } from "zod";
import {
  createJobCommentRpcSchema,
  createMembershipCommandSchema,
  createPolicyVersionCommandSchema,
  setDepartmentAvailabilityCommandSchema,
  createProjectBindingCommandSchema,
  removeMembershipCommandSchema,
  saveAgentProfileCommandSchema,
  saveDepartmentProfileCommandSchema,
} from "../../shared/contracts";

const emptyObjectSchema = z.object({}).strict();

export const CLI_OPERATIONS = {
  assessVerification: { input: verificationAdviceInputSchema, summary: "Необязательная оценка промежуточной проверки законченного блока: полный diff, риск и TypeSafe; не приёмка и не отмена финальных тестов" },
  getLeadState: { input: leadStateQuerySchema, summary: "Цель, решение, дети и готовность сдачи; children имеют nextOffset" },
  recordLessonFeedback: { input: recordLessonFeedbackSchema, summary: "Оценка применения урока с доказательствами; CAS по ревизии знания" },
  recordLeadDecision: { input: recordLeadDecisionSchema, summary: "Решение руководителя: неизвестное, причина, действие и следующая проверка; CAS по decisionRevision" },
  submitJobResult: { input: submitJobResultSchema, summary: "Явно сдать точную опубликованную версию; expectedRevision задачи, artifactId/version/hash/comment" },
  getSessionPolicy: { input: getSessionPolicyInputSchema, summary: "Режим обычных чатов: проект, папка, этот тред" },
  saveSessionPolicy: { input: saveSessionPolicyInputSchema, summary: "Задать режим чатов проекта, папки, этого треда или черновика нового чата" },
  listWorkspace: { input: listWorkspaceInputSchema, summary: "Снимок workspace, включая полный PolicyVersion" },
  listBbCatalog: { input: emptyObjectSchema, summary: "Каталог BB-проектов и окружений; label политики не есть права" },
  listCapabilityCatalog: { input: capabilityCatalogInputSchema, summary: "Read-only навыки/MCP из SDK" },
  getJob: { input: getJobInputSchema, summary: "Карточка задачи по id или AG-ключу" },
  listDashboardUsage: {
    input: listDashboardUsageInputSchema,
    summary: "Расход токенов и оценка стоимости: rootJobId — задача вместе с подзадачами",
  },
  getAgent: { input: getAgentInputSchema, summary: "Сотрудник и текущая версия" },
  getDepartment: { input: getDepartmentInputSchema, summary: "Отдел, процесс и membership" },
  listArtifactVersions: { input: listArtifactVersionsInputSchema, summary: "Версии артефакта задачи" },
  createPolicyVersion: { input: createPolicyVersionCommandSchema, summary: "Неизменяемая политика: полный payload, не имя" },
  provisionAgent: { input: provisionAgentRpcSchema, summary: "Создать сотрудника с первой версией" },
  saveAgentProfile: { input: saveAgentProfileCommandSchema, summary: "Атомарно сохранить профиль сотрудника (CAS)" },
  provisionDepartment: { input: provisionDepartmentRpcSchema, summary: "Создать отдел с процессом и lead membership" },
  saveDepartmentProfile: { input: saveDepartmentProfileCommandSchema, summary: "Атомарно сохранить отдел (CAS)" },
  addMembership: { input: createMembershipCommandSchema, summary: "Добавить сотрудника в отдел" },
  removeMembership: { input: removeMembershipCommandSchema, summary: "Убрать сотрудника из отдела" },
  createProjectBinding: { input: createProjectBindingCommandSchema, summary: "Привязать существующий каталог BB" },
  linkDepartment: { input: linkDepartmentRpcSchema, summary: "Связать отдел с привязкой проекта" },
  unlinkDepartment: { input: unlinkDepartmentRpcSchema, summary: "Убрать отдел из выбранных отделов проекта" },
  archiveProjectBinding: { input: bindingLifecycleRpcSchema, summary: "Отключить проект: история остаётся, новые задачи и запуски закрыты" },
  restoreProjectBinding: { input: bindingLifecycleRpcSchema, summary: "Вернуть отключённый проект" },
  deleteProjectBinding: { input: bindingLifecycleRpcSchema, summary: "Удалить подключение проекта без задач; BB-проект и файлы не трогаются" },
  setDepartmentAvailability: { input: setDepartmentAvailabilityCommandSchema, summary: "Отдел для всех проектов (all) или только для выбранных (selected)" },
  getWorkRules: { input: getWorkRulesInputSchema, summary: "Правила работы уровня: agency, department:<id> или agent:<id> — сохранённые, действующие и их источник" },
  listTemplates: { input: emptyObjectSchema, summary: "Шаблоны форм: регламент, должностные инструкции по типам ролей, бриф и критерии; custom — задан владельцем" },
  saveTemplate: { input: saveTemplateInputSchema, summary: "Сохранить шаблон (text) или сбросить к стандартному (text: null); expectedRevision из listTemplates" },
  getAgencyRules: { input: emptyObjectSchema, summary: "Общие правила Агентства: действующая версия и история" },
  saveAgencyRules: { input: saveAgencyRulesInputSchema, summary: "Новая версия общих правил Агентства; пустой текст выключает слой. expectedVersion = latestVersion" },
  listKnowledge: { input: listKnowledgeInputSchema, summary: "Знания Агентства, отделов, проектов и разделов: принятые (идут в запуски по области), предложения и архив; фильтр scopeKind/scopeId/parentBindingId/status" },
  saveKnowledge: { input: saveKnowledgeInputSchema, summary: "Материал знаний Агентства, отдела, проекта или раздела; из треда сотрудника сохраняется как предложение до решения владельца" },
  listIdeas: { input: listIdeasInputSchema, summary: "Склад идей и туду: фильтр bindingId / bbProjectId / sectionId / kind / status; в ответе title, projectPath и relativePath для ссылок в чате" },
  getIdea: { input: z.object({ id: z.string() }).strict(), summary: "Одна идея целиком: markdown-тело и путь файла в проекте" },
  saveIdea: { input: saveIdeaInputSchema, summary: "Записать обсуждённую идею или туду: база Агентства и файл .bb/agency/ideas/<id>.md в корне привязанного проекта" },
  setIdeaStatus: { input: setIdeaStatusInputSchema, summary: "Сменить статус идеи: open, parked, done, archived. Для done обязателен resolution (что сделали) и желателен closedThreadId" },
  spawnIdeaThread: { input: spawnIdeaThreadInputSchema, summary: "Создать видимый тред BB по идее: штатный композер, не скрытый запуск сотрудника" },
  getDecisionSettings: { input: emptyObjectSchema, summary: "Оценщик: настройки, точки решения, журнал, состояние ключа и имена переменных Env Catalog" },
  saveDecisionSettings: { input: saveDecisionSettingsInputSchema, summary: "Включить оценщика, выбрать модель, имя ключа и точки решения; expectedRevision из getDecisionSettings" },
  testDecisionModel: { input: emptyObjectSchema, summary: "Задать оценщику один вопрос и показать ответ, уверенность и время" },
  listTrace: { input: traceQuerySchema, summary: "Трассировка задачи и подзадач: решения, причины, попытки, длительность и повторы; только владелец" },
  getJobDiagnostics: { input: jobDiagnosticsQuerySchema, summary: "Диагностика порученной линии: прошлые замечания, попытки, trace и видимые сообщения; руководитель или владелец" },
  listDecisionLog: { input: z.object({ limit: z.number().int().min(1).max(200).optional() }).strict(), summary: "Журнал оценщика: точка, задача, исход, ответы с уверенностью и время" },
  probeDecisionPoints: { input: emptyObjectSchema, summary: "Живая проверка оценки на входе, подсказки к запуску и привратника сдачи на учебных брифах без запуска сотрудника" },
  listGoals: { input: emptyObjectSchema, summary: "Цели над главными задачами с прогрессом" },
  setJobGoal: { input: z.object({ jobId: z.string(), goalId: z.string().nullable() }).strict(), summary: "Привязать главную задачу к цели (goalId null — отвязать)" },
  searchJobs: { input: z.object({ query: z.string().max(200), limit: z.number().int().min(1).max(200).optional() }).strict(), summary: "Поиск задач по ключу, названию, брифу и комментариям, включая архив" },
  agentMetrics: { input: z.object({ agentId: z.string() }).strict(), summary: "Показатели сотрудника: загрузка, закрытые, доля без доработок, срок, расход за 30 дней" },
  getSkillPins: { input: emptyObjectSchema, summary: "Закреплённые версии навыков против текущих: чем отличаются и что мешает запуску" },
  pinSkills: { input: emptyObjectSchema, summary: "Закрепить текущие версии навыков; только владелец, не из треда сотрудника" },
  getWorkerContext: { input: workerContextQuerySchema, summary: "Служебный контекст сотрудника или отдела (VK)" },
  saveWorkerContext: { input: saveWorkerContextSchema, summary: "Настроить служебные навыки и плагины; CAS, только владелец" },
  getSkillPool: { input: z.object({ departmentId: z.string() }).strict(), summary: "Библиотека навыков отдела и журнал выдач: что отдел вправе поднять под задание" },
  setSkillPool: { input: z.object({ departmentId: z.string(), skillIds: z.array(z.string()).max(60), mode: z.enum(["replace", "merge"]).optional() }).strict(), summary: "Библиотека навыков отдела: mode merge дописывает, replace (по умолчанию) заменяет список целиком; правит владелец или руководитель этого отдела" },
  listSkillGrants: { input: z.object({ departmentId: z.string().optional(), agentId: z.string().optional() }).strict(), summary: "Журнал выдач: кому и какой навык открыли под задачу и кто решил" },
  getKnowledge: { input: z.object({ id: z.string() }).strict(), summary: "Одна запись знаний целиком: в запуск приходит только сводка, тело читается так" },
  setKnowledgeStatus: { input: z.object({ id: z.string(), expectedRevision: z.number().int(), status: z.enum(["proposal", "accepted", "archived"]) }).strict(), summary: "Принять запись или убрать её в архив; руководитель отдела решает только по своему отделу (урок, процедура, справка)" },
  listWorkProfiles: { input: z.object({ bbProjectId: z.string().optional() }).strict(), summary: "Профили работ проекта: как здесь делают такой результат — голос, стиль, эталоны" },
  saveWorkProfile: { input: z.object({ bbProjectId: z.string(), key: z.string(), expectedRevision: z.number().int(), title: z.string(), triggers: z.array(z.string()).optional(), body: z.string(), samples: z.array(z.object({ label: z.string(), ref: z.string(), note: z.string().optional() }).strict()).optional(), acceptance: z.string().optional() }).strict(), summary: "Сохранить профиль работы проекта; expectedRevision из listWorkProfiles, 0 для нового" },
  deleteWorkProfile: { input: z.object({ bbProjectId: z.string(), key: z.string() }).strict(), summary: "Удалить профиль работы проекта" },
  getProjectPassport: { input: z.object({ bbProjectId: z.string() }).strict(), summary: "Паспорт проекта: что это за проект, для кого и чего здесь не делают; история редакций" },
  savePassport: { input: savePassportInputSchema, summary: "Переписать паспорт проекта руками; expectedRevision из getProjectPassport, 0 для нового" },
  buildProjectPassport: { input: z.object({ bbProjectId: z.string() }).strict(), summary: "Собрать паспорт проекта заново по знаниям, профилям, целям и принятым результатам" },
  rollbackPassport: { input: z.object({ bbProjectId: z.string(), revision: z.number().int() }).strict(), summary: "Вернуть прежнюю редакцию паспорта проекта" },
  getPassportSettings: { input: emptyObjectSchema, summary: "Настройки писаря паспорта: модель, имя ключа, через сколько принятых задач пересобирать" },
  savePassportSettings: { input: savePassportSettingsInputSchema, summary: "Включить писаря паспорта, выбрать модель и порог пересборки; expectedRevision из getPassportSettings" },
  agentModels: { input: emptyObjectSchema, summary: "Модели сотрудников против того, что подключено в этом BB: exact, substituted (есть замена), missing (замены нет)" },
  repairAgentModels: { input: z.object({ agentIds: z.array(z.string()).max(200).optional() }).strict(), summary: "Перевести сотрудников на доступные модели: новая версия профиля с ближайшей подключённой моделью" },
  listArchivedJobs: { input: z.object({ limit: z.number().int().min(1).max(500).optional(), offset: z.number().int().min(0).optional() }).strict(), summary: "Архив закрытых задач" },
  starterKit: { input: z.object({ language: z.enum(["ru", "en"]).optional() }).strict(), summary: "Стартовые отделы и сотрудники: что есть в наборе, что установлено, сколько записей можно перевести" },
  installStarterKit: { input: installStarterKitInputSchema, summary: "Установить выбранные стартовые отделы с сотрудниками; language по умолчанию — язык Агентства" },
  translateStarterKit: { input: z.object({ language: z.enum(["ru", "en"]).optional() }).strict(), summary: "Перевести стартовые отделы и сотрудников, которых владелец не менял, на язык; изменённые остаются" },
  recordLifecycle: { input: recordLifecycleInputSchema, summary: "Можно ли удалить отдел или сотрудника и почему нет; дата архива отдела" },
  archiveDepartment: { input: z.object({ departmentId: z.string().max(80) }).strict(), summary: "Отдел в архив: уходит из маршрута и форм, история остаётся; нужны закрытые задачи" },
  restoreDepartment: { input: z.object({ departmentId: z.string().max(80) }).strict(), summary: "Вернуть отдел из архива" },
  deleteDepartment: { input: z.object({ departmentId: z.string().max(80) }).strict(), summary: "Удалить отдел без истории задач; сотрудники остаются" },
  deleteAgent: { input: z.object({ agentId: z.string().max(80) }).strict(), summary: "Удалить сотрудника без истории работы; иначе — архив через agent save со state archived" },
  notifyOwner: {
    input: notifyOwnerInputSchema,
    summary: "Сообщение владельцу: «Входящие → Сообщения» и Telegram, если включён; dedupeKey доставляет одно сообщение один раз",
  },
  listOwnerMessages: { input: z.object({ limit: z.number().int().min(1).max(500).optional() }).strict(), summary: "Сообщения владельцу, новые сверху, и число непрочитанных" },
  markOwnerMessagesRead: { input: z.object({ ids: z.array(z.string().max(80)).max(500).optional() }).strict(), summary: "Отметить сообщения прочитанными; без ids — все" },
  ownerDigest: {
    input: ownerDigestInputSchema,
    summary: "Сводка (summary: sinceHours) или сторож (watchdog: задачи ждут человека дольше stuckHours); notify:true отправляет владельцу",
  },
  listScriptTemplates: { input: emptyObjectSchema, summary: "Шаблоны скриптов для cron/launchd: сводка за день, сторож, регулярная задача из внешних данных" },
  listBudgets: { input: emptyObjectSchema, summary: "Бюджеты в месяц: уровни с лимитом, оценка расхода за календарный месяц (UTC) и процент" },
  providerUsage: { input: emptyObjectSchema, summary: "Расход подписок CLI по данным BB: план, окна, процент и сброс; countsTokens — считает ли Агентство токены этого CLI" },
  saveWorkRules: { input: saveWorkRulesCommandSchema, summary: "Сохранить правила уровня целиком: отсутствующий ключ возвращает значение по умолчанию" },
  readProjectRules: { input: readProjectRulesInputSchema, summary: "Прочитать правила проекта (.bb/AGENTS.md) на машине привязки" },
  saveProjectRules: { input: saveProjectRulesInputSchema, summary: "Сохранить правила проекта, если файл не менялся после чтения (expectedHash)" },
  createJob: { input: createJobRpcSchema, summary: "Создать задачу; state задаёт переход, не create" },
  updateJob: { input: updateJobRpcSchema, summary: "Обновить поля задачи, включая назначение" },
  addJobDependency: {
    input: addJobDependencyRpcSchema,
    summary: "Задача ждёт другую: запуск откладывается, из очереди запуска стартует сама, когда та готова",
  },
  removeJobDependency: { input: removeJobDependencyRpcSchema, summary: "Убрать зависимость задачи" },
  setJobNextStep: {
    input: setJobNextStepRpcSchema,
    summary: "Следующий шаг: когда задача готова, Агентство само создаёт задачу отделу рядом с ней, прикладывает принятые версии и ставит в очередь; step null — убрать",
  },
  transitionJob: { input: transitionJobRpcSchema, summary: "Сменить состояние задачи" },
  createArtifact: { input: createArtifactRpcSchema, summary: "Создать реестровую запись артефакта" },
  publishArtifactVersion: { input: publishArtifactRpcSchema, summary: "Опубликовать версию файла" },
  attachJobInput: {
    input: attachJobInputRpcSchema,
    summary: "Привязать published input version к target job; host/root не из caller",
  },
  reportNeedsInput: {
    input: reportNeedsInputRpcSchema,
    summary: "Typed worker wait: bind verified job/attempt/thread/launch; Job+attempt waiting_input; no accept",
  },
  answerNeedsInput: {
    input: answerNeedsInputRpcSchema,
    summary: "Ответ на needsInput: waitId текущего цикла, тот же thread/attempt, official send, без spawn и accept",
  },
  staleAnswer: {
    input: staleAnswerRpcSchema,
    summary: "Ответ агента origin-чата на зависшую задачу: close|cancel|keep|escalate; expectedJobRevision обязателен",
  },
  acceptArtifactVersion: { input: acceptArtifactRpcSchema, summary: "Принять текущую версию и закрыть станцию" },
  openArtifact: { input: openArtifactRpcSchema, summary: "Открыть версию; bytes в CLI не печатаются" },
  enqueueLaunch: {
    input: enqueueLaunchRpcSchema,
    summary: "Поставить задачу в очередь запуска: стартует сама, когда лимиты параллельности и бюджета позволят; backlog переводится в queued",
  },
  dequeueLaunch: { input: dequeueLaunchRpcSchema, summary: "Убрать задачу из очереди запуска" },
  prepareLaunch: {
    input: prepareLaunchRpcSchema,
    summary: "Prepare launch на текущем instance; native threads.spawn (скрытый plugin-тред); не respawn",
  },
  getLaunch: { input: getLaunchRpcSchema, summary: "Прочитать launch receipt по launchId или attemptId" },
  reconcileLaunch: { input: reconcileLaunchRpcSchema, summary: "Сверить thread по pluginMetadata.agencyLaunchId; не respawn" },
  interpretWorkerCompletion: {
    input: interpretWorkerCompletionRpcSchema,
    summary: "Сверить completion с core get + open/hash; caller flags не принимаются",
  },
  listJobAttempts: {
    input: listJobAttemptsRpcSchema,
    summary: "Список scoped RunAttempt по jobId; не выдумывает строки",
  },
  getIsolationReadiness: {
    input: getIsolationReadinessRpcSchema,
    summary: "Native threads.spawn + assigned CLI; любой CLI, подключённый в BB, если его разрешают политики проекта и сотрудника",
  },
  recoverJob: { input: recoverJobCommandSchema, summary: "Решение руководителя: причина, исправление, проверка; один возврат или запуск исходной задачи" },
  returnJobForRework: {
    input: returnJobForReworkCommandSchema,
    summary: "Вернуть версию на доработку: замечание уходит в тред исполнителя, задача снова в работе",
  },
  cancelLaunch: {
    input: cancelLaunchCommandSchema,
    summary: "Observed stop exact thread; attempt canceled + Job blocked; no spawn, Job not canceled",
  },
  saveEventDefinition: { input: saveEventDefinitionCommandSchema, summary: "Зарегистрировать topic/namespace EventDefinition" },
  saveEventSource: { input: saveEventSourceCommandSchema, summary: "Источник событий проекта; выключенный режет ingest" },
  saveRuleVersion: { input: saveRuleVersionCommandSchema, summary: "Новая версия правила; старые match не переписываются" },
  ingestInboxEvent: { input: ingestInboxEventCommandSchema, summary: "Typed inbox; не replay alpha notify" },
  dispatchTick: { input: dispatchTickCommandSchema, summary: "Оценить inbox→match→intent; live по умолчанию false" },
  listEventDefinitions: { input: listDispatcherCatalogCommandSchema, summary: "Каталог EventDefinition: topic + human label" },
  listEventSources: { input: listDispatcherCatalogCommandSchema, summary: "Каталог источников событий проекта" },
  listRuleVersions: { input: listDispatcherCatalogCommandSchema, summary: "Последние версии правил с label=ruleId" },
  listActionIntents: { input: listActionIntentsCommandSchema, summary: "Очередь ActionIntent + join label/topic/rule" },
  claimActionIntent: { input: claimActionIntentCommandSchema, summary: "CAS lease + fence; live=false не enqueue; unavailable не жжёт retry" },
  approveActionIntent: { input: approveActionIntentCommandSchema, summary: "CAS approve: expectedRevision + state=awaiting_approval" },
  completeActionIntent: { input: completeActionIntentCommandSchema, summary: "Завершить claimed только с текущим fencing token/generation" },
  createJobComment: {
    input: createJobCommentRpcSchema,
    summary: "Комментарий в историю задачи; kind=comment; автор сотрудник только с proof thread",
  },
} as const satisfies Record<string, { input: ZodType; summary: string }>;

export type CliRoutedOperation = keyof typeof CLI_OPERATIONS;
/** Dispatch surface in register.ts. createJobComment is CLI-routed via jobComment port, not handlers[op]. */
export type CliOperation = Exclude<CliRoutedOperation, "createJobComment">;

export const CLI_OPERATION_NAMES = Object.keys(CLI_OPERATIONS) as CliRoutedOperation[];

export function isCliOperation(value: string): value is CliRoutedOperation {
  return Object.hasOwn(CLI_OPERATIONS, value);
}
