import { SearchInput } from "./shared";
import { useMemo, useState } from "react";
import { CronExpressionParser } from "cron-parser";
import { WebhookEditor } from "./webhook";
import { EventLabel, EventPicker } from "./event-catalog";
import { Switch } from "../../../components/ui/switch";
import type { Automation } from "./data";
import { Button, TextField, Choice, PageHead, TabBar, Panel, Rows, Field, Collection, Input } from "./shared";
export function AutomationsPage({ items, open, create, update }: {items:Automation[];open:(id:string)=>void;create:()=>void;update:(a:Automation)=>void}) {
 const [q,setQ]=useState("");const filtered=items.filter(a=>(a.name+a.project+a.department).toLowerCase().includes(q.toLowerCase()));
 return <div className="space-y-4"><PageHead title="Автоматизации" description="Когда и кому система передаёт работу."><Button onClick={create}>Создать автоматизацию</Button></PageHead><SearchInput className="max-w-xs" aria-label="Поиск автоматизаций" placeholder="Найти правило…" value={q} onChange={e=>setQ(e.target.value)}/><Collection columns={["Правило","Включено","Триггер","Получатель","Проект"]} rows={filtered.map(a=>({id:a.id,open:()=>open(a.id),name:<span className="font-medium">{a.name}</span>,cells:[<Switch aria-label={`Включить ${a.name} в примере`} checked={a.enabled} onCheckedChange={enabled=>update({...a,enabled})}/>,a.kind==="cron"?a.cron:a.kind==="event"?<EventLabel topic={a.topic}/>:a.kind==="webhook"?"Внешний webhook":"Вручную",a.department,a.project]}))}/><p className="text-xs text-muted-foreground">Расписания и переключатели пока действуют только в примере.</p></div>;
}
export function AutomationDetail({ item, update, back, notice }: {item:Automation;update:(a:Automation)=>void;back:()=>void;notice:(s:string)=>void}) {
 const [tab,setTab]=useState("Триггер");const [missed,setMissed]=useState("Последний пропущенный");const [overlap,setOverlap]=useState("Поставить в очередь");const [tries,setTries]=useState("2");const [testTopic,setTestTopic]=useState("job.ready_for_review");const [verdict,setVerdict]=useState("");
 const dates=useMemo(()=>{try{const e=CronExpressionParser.parse(item.cron,{tz:item.timezone});return Array.from({length:3},()=>e.next().toDate().toLocaleString("ru-RU",{timeZone:item.timezone}));}catch{return [];}},[item.cron,item.timezone]);
 return <div className="space-y-5"><Button variant="ghost" size="sm" onClick={back}>← Автоматизации</Button><PageHead title={item.name}><Button variant="outline" onClick={()=>setTab("Проверка")}>Проверить правило</Button><Button onClick={()=>notice("Черновик автоматизации сохранён в прототипе. Исполнение выключено.")}>Сохранить</Button></PageHead><TextField label="Название автоматизации" value={item.name} onChange={name=>update({...item,name})}/><TabBar value={tab} onChange={setTab} tabs={["Триггер","Действие","Ограничения","Проверка","История"]}/>
 <div className="max-w-4xl space-y-4">{tab==="Триггер"&&<><Field label="Способ активации"><Choice label="Способ активации" value={item.kind} onChange={kind=>update({...item,kind})} options={[{value:"event",label:"Событие или уведомление"},{value:"cron",label:"По расписанию"},{value:"webhook",label:"Внешний webhook"},{value:"manual",label:"Вручную"}]}/></Field>
 {item.kind==="event"&&<Panel title="Слушать событие"><EventPicker value={item.topic} onChange={topic=>update({...item,topic})}/></Panel>}
 {item.kind==="cron"&&<><div className="grid gap-4 md:grid-cols-2"><TextField label="Cron (пять полей)" value={item.cron} onChange={cron=>update({...item,cron})}/><Field label="Часовой пояс"><Choice label="Часовой пояс" value={item.timezone} onChange={timezone=>update({...item,timezone})} options={["Europe/Madrid","Europe/Moscow","UTC"]}/></Field></div><Panel title="Ближайшие срабатывания — предпросмотр">{dates.length?dates.map(d=><p className="py-1 text-sm" key={d}>{d}</p>):<p role="alert" className="text-sm text-destructive">Проверьте cron-выражение и часовой пояс.</p>}</Panel></>}
 {item.kind==="webhook"&&<WebhookEditor item={item} update={update}/>}
 {item.kind==="manual"&&<Panel title="По команде"><p className="text-sm">Запуск из карточки, управляющего чата или через CLI. Все способы используют одно правило и ограничения.</p></Panel>}
 </>}
 {tab==="Действие"&&<div className="space-y-4"><Field label="Проект"><Choice label="Проект автоматизации" value={item.project} onChange={project=>update({...item,project})} options={["SelfyStudio","BB-сервис"]}/></Field><Field label="Передать в отдел"><Choice label="Отдел автоматизации" value={item.department} onChange={department=>update({...item,department})} options={["Маркетинг","Редакция","Дизайн","Исследования"]}/></Field><TextField label="Шаблон поручения" multiline value={item.prompt} onChange={prompt=>update({...item,prompt})}/><Panel title="Контекст из события"><p className="text-sm">Проект, исходная задача, версия результата и ссылки на материалы будут переданы по проверяемому контракту.</p></Panel></div>}
 {tab==="Ограничения"&&<div className="space-y-4"><Field label="Если расписание пропущено"><Choice label="Пропущенное расписание" value={missed} onChange={setMissed} options={["Пропустить","Последний пропущенный","Догнать с ограничением"]}/></Field><Field label="Если предыдущая задача работает"><Choice label="Наложение запусков" value={overlap} onChange={setOverlap} options={["Пропустить","Поставить в очередь","Параллельно в пределах лимита"]}/></Field><TextField label="Максимум повторных попыток" type="number" value={tries} onChange={setTries}/><Panel title="Защита от циклов"><p className="text-sm">Повторный eventId не создаёт новую задачу. Причинная цепочка и предел возвратов не дают правилам бесконечно будить друг друга.</p></Panel></div>}
 {tab==="Проверка"&&<Panel title="Пробное уведомление"><EventPicker label="Пробное событие" value={testTopic} onChange={setTestTopic}/><Button className="mt-3" onClick={()=>setVerdict(item.kind==="event"?(testTopic===item.topic?`Совпадение: ${item.project} → ${item.department}. Создалось бы поручение по шаблону.`:"Не совпадает: это правило не сработало бы."):item.kind==="cron"?(dates.length?"Расписание корректно. Создалось бы поручение в указанное время.":"Расписание некорректно."):"Правило ожидает ручного или проверенного внешнего сигнала.")}>Показать маршрут</Button>{verdict&&<p role="status" className="mt-4 text-sm">{verdict} Ничего не отправлено.</p>}</Panel>}
 {tab==="История"&&<Panel title="Пример истории"><Rows rows={[["Принято","Уведомление evt-204"],["Проверено","Условия совпали"],["Результат","Поручение назначено редактору"]]}/><p className="mt-3 text-xs text-muted-foreground">Демонстрационная цепочка. Реальных запусков нет.</p></Panel>}
 </div></div>;
}
