import { TelegramActionChoice } from "./telegram";
import { ScheduleEditor, scheduleName } from "./schedule";
import { SearchInput } from "./shared";
import { useEffect, useMemo, useState } from "react";
import { CronExpressionParser } from "cron-parser";
import { WebhookEditor } from "./webhook";
import { EventLabel, EventPicker } from "./event-catalog";
import { Switch } from "../../../components/ui/switch";
import type { Automation } from "./data";
import { Button, TextField, Choice, PageHead, TabBar, Panel, Rows, Field, Collection, Input, Empty } from "./shared";
export function AutomationsPage({ items, open, create, update }: {items:Automation[];open:(id:string)=>void;create:()=>void;update:(a:Automation)=>void}) {
 const [q,setQ]=useState("");const filtered=items.filter(a=>(a.name+a.project+a.department).toLowerCase().includes(q.toLowerCase()));
 return <div className="space-y-4"><PageHead title="Автоматизации" description="Когда и кому система передаёт работу."><Button onClick={create}>Создать автоматизацию</Button></PageHead><SearchInput className="max-w-xs" aria-label="Поиск автоматизаций" placeholder="Найти правило…" value={q} onChange={e=>setQ(e.target.value)}/><Collection columns={["Правило","Включено","Триггер","Получатель","Проект"]} rows={filtered.map(a=>({id:a.id,open:()=>open(a.id),name:<span className="font-medium">{a.name}</span>,cells:[<Switch aria-label={`Включить ${a.name} в примере`} checked={a.enabled} onCheckedChange={enabled=>update({...a,enabled})}/>,a.kind==="cron"?<span>{scheduleName(a.cron)}<span className="block text-xs text-muted-foreground">{a.timezone}</span></span>:a.kind==="event"?<EventLabel topic={a.topic}/>:a.kind==="webhook"?"Внешний webhook":"Вручную",a.department,a.project]}))}/><p className="text-xs text-muted-foreground">Расписания и переключатели пока действуют только в примере.</p></div>;
}
export function AutomationDetail({ item, update, back, notice }: {item:Automation;update:(a:Automation)=>void;back:()=>void;notice:(s:string)=>void}) {
 const [tab,setTab]=useState("Триггер");const missed=item.missed||"Последний пропущенный";const setMissed=(missed:string)=>update({...item,missed});const overlap=item.overlap||"Поставить в очередь";const setOverlap=(overlap:string)=>update({...item,overlap});const tries=item.tries||"2";const setTries=(tries:string)=>update({...item,tries});const [testTopic,setTestTopic]=useState("job.ready_for_review");const [verdict,setVerdict]=useState("");
 useEffect(()=>setVerdict(""),[item,testTopic]);
 const dates=useMemo(()=>{try{if(item.cron.trim().split(/\s+/).length!==5)return [];const e=CronExpressionParser.parse(item.cron,{tz:item.timezone});return Array.from({length:3},()=>e.next().toDate().toLocaleString("ru-RU",{timeZone:item.timezone}));}catch{return [];}},[item.cron,item.timezone]);
 return <div className="space-y-5"><Button variant="ghost" size="sm" onClick={back}>← Автоматизации</Button><PageHead title={item.name}><Button variant="outline" onClick={()=>update({...item,enabled:!item.enabled})}>{item.enabled?"Приостановить":"Включить в примере"}</Button><Button variant="outline" onClick={()=>setTab("Проверка")}>Проверить правило</Button><Button onClick={()=>notice("Черновик автоматизации сохранён в прототипе. Исполнение выключено.")}>Сохранить</Button></PageHead><div className="max-w-4xl rounded-lg border border-border bg-muted/30 p-4"><p className="text-sm"><strong>Когда:</strong> {item.kind==="cron"?scheduleName(item.cron):item.kind==="event"?<EventLabel topic={item.topic}/>:item.kind==="webhook"?"Получено внешнее уведомление":"По вашей команде"}</p><p className="mt-2 text-sm"><strong>Кому:</strong> {item.actionKind?.startsWith("telegram.")?"Тема проекта в Telegram":item.department} · {item.project}</p><p className="mt-2 text-xs text-muted-foreground">{item.enabled?"Включено в примере":"На паузе в примере"}. Реальное исполнение ещё не подключено.</p></div><div className="max-w-4xl"><TextField label="Название автоматизации" value={item.name} onChange={name=>update({...item,name})}/></div><TabBar value={tab} onChange={setTab} tabs={["Триггер","Действие","Ограничения","Проверка","История"]}/>
 <div className="max-w-4xl space-y-4">{tab==="Триггер"&&<><Field label="Способ активации"><Choice label="Способ активации" value={item.kind} onChange={kind=>update({...item,kind})} options={[{value:"event",label:"Событие или уведомление"},{value:"cron",label:"По расписанию"},{value:"webhook",label:"Внешний webhook"},{value:"manual",label:"Вручную"}]}/></Field>
 {item.kind==="event"&&<Panel title="Слушать событие"><EventPicker value={item.topic} onChange={topic=>update({...item,topic})}/></Panel>}
 {item.kind==="cron"&&<><ScheduleEditor cron={item.cron} timezone={item.timezone} onChange={patch=>update({...item,...patch})}/><Panel title="Ближайшие срабатывания — предпросмотр">{dates.length?dates.map(d=><p className="py-1 text-sm" key={d}>{d}</p>):<p role="alert" className="text-sm text-destructive">Проверьте cron-выражение и часовой пояс.</p>}</Panel></>}
 {item.kind==="webhook"&&<WebhookEditor item={item} update={update}/>}
 {item.kind==="manual"&&<Panel title="По команде"><p className="text-sm">Запуск из карточки, управляющего чата или через CLI. Все способы используют одно правило и ограничения.</p></Panel>}
 </>}
 {tab==="Действие"&&<div className="space-y-4"><TelegramActionChoice value={item.actionKind||"agent"} onChange={actionKind=>update({...item,actionKind})}/><Field label="Проект"><Choice label="Проект автоматизации" value={item.project} onChange={project=>update({...item,project})} options={["SelfyStudio","BB-сервис"]}/></Field>{(!item.actionKind||item.actionKind==="agent")&&<Field label="Передать в отдел"><Choice label="Отдел автоматизации" value={item.department} onChange={department=>update({...item,department})} options={["Маркетинг","Редакция","Дизайн","Исследования"]}/></Field>}<TextField label={item.actionKind?.startsWith("telegram.")?"Текст уведомления":"Шаблон поручения"} multiline value={item.prompt} onChange={prompt=>update({...item,prompt})}/><Panel title="Контекст из события"><p className="text-sm">Проект, исходная задача, версия результата и ссылки на материалы будут переданы по проверяемому контракту.</p></Panel></div>}
 {tab==="Ограничения"&&<div className="space-y-4">{item.kind==="cron"&&<Field label="Если расписание пропущено"><Choice label="Пропущенное расписание" value={missed} onChange={setMissed} options={["Пропустить","Последний пропущенный","Догнать с ограничением"]}/></Field>}<Field label="Если предыдущая задача работает"><Choice label="Наложение запусков" value={overlap} onChange={setOverlap} options={["Пропустить","Поставить в очередь","Оставить последнее ожидающее"]}/></Field><TextField label="Максимум повторных попыток" type="number" value={tries} onChange={value=>setTries(String(Math.max(0,Math.min(3,Number(value)||0))))}/><Panel title="Защита от циклов"><p className="text-sm">Повторный eventId не создаёт новую задачу. Причинная цепочка и предел возвратов не дают правилам бесконечно будить друг друга.</p></Panel></div>}
 {tab==="Проверка"&&<Panel title="Пробное уведомление">{item.kind==="event"?<EventPicker label="Пробное событие" value={testTopic} onChange={setTestTopic}/>:<p className="text-sm">{item.kind==="cron"?"Проверка покажет корректность расписания.":item.kind==="webhook"?"Проверка JSON и условий находится в настройках источника.":"Проверьте получателя и текст поручения перед ручным запуском."}</p>}<Button className="mt-3" onClick={()=>{if(item.kind==="webhook"){setTab("Триггер");return;}setVerdict(!item.enabled?"Правило на паузе: поручение не создаётся.":item.kind==="event"?(testTopic===item.topic?`Совпадение: ${item.project} → ${item.department}. Выполнилось бы выбранное действие по шаблону.`:"Не совпадает: это правило не сработало бы."):item.kind==="cron"?(dates.length?"Расписание корректно. Создалось бы поручение в указанное время.":"Расписание некорректно."):"Правило ожидает ручного или проверенного внешнего сигнала.");}}>Показать маршрут</Button>{verdict&&<p role="status" className="mt-4 text-sm">{verdict} Ничего не отправлено.</p>}</Panel>}
 {tab==="История"&&<Empty title="Правило ещё не запускалось" description="Здесь появятся срабатывания, причины пропусков и ссылки на созданные задачи."/>}
 </div></div>;
}
