import { useState } from 'react';
import { experimental_ProviderModelPicker as ProviderModelPicker } from '@get-bb/plugin-sdk/app';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '../../../components/ui/dialog';
import { Button, Choice, Field, TextField } from './shared';
import type { Agent, Job, TaskFile } from './data';
import { STAGE1_UNAVAILABLE } from '../data';
export function Handoff({job,agents,files,update,runtimeAvailable=true}:{job:Job;agents:Agent[];files:TaskFile[];update:(j:Job)=>void;runtimeAvailable?:boolean}) {
 const [open,setOpen]=useState(false);const [target,setTarget]=useState(agents.find(a=>a.name===job.agent)?.id||agents[0]?.id||'');
 const agent=agents.find(a=>a.id===target);const [selection,setSelection]=useState(job.execution||agent?.selection||{providerId:'codex',model:'',reasoningLevel:'medium' as const});const[reason,setReason]=useState('');
 const submit=()=>{if(!agent||!reason.trim())return;update({...job,agent:agent.name,department:agent.department,execution:selection,state:'queued',activity:[...(job.activity||[]),{id:crypto.randomUUID(),kind:'event',at:new Date().toISOString(),text:`Передача: ${job.agent} → ${agent.name}. CLI: ${selection.providerId}; модель: ${selection.model||'по профилю'}. Причина: ${reason.trim()}. Материалы: ${files.map(f=>`${f.name} v${f.version||1}`).join(', ')||'описание задачи'}. Назначение сохранено в примере; новый запуск не создан.`}]});setOpen(false);setReason('');};
 if(!runtimeAvailable)return <div className="max-w-sm space-y-1"><Button size="sm" variant="outline" disabled>Передать работу</Button><p className="text-xs text-muted-foreground">{STAGE1_UNAVAILABLE.autonomy}</p></div>;
 return <><Button size="sm" variant="outline" onClick={()=>{const a=agents.find(a=>a.name===job.agent)||agents[0];if(a){setTarget(a.id);setSelection(job.execution||a.selection);}setOpen(true);}}>Передать работу</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Передать задачу</DialogTitle><DialogDescription>Новый исполнитель получит поручение и материалы. История предыдущих попыток сохранится.</DialogDescription></DialogHeader><div className="space-y-4"><Field label="Сотрудник"><Choice label="Новый исполнитель" value={target} onChange={id=>{setTarget(id);const a=agents.find(a=>a.id===id);if(a)setSelection(a.selection);}} options={agents.filter(a=>a.enabled).map(a=>({value:a.id,label:`${a.name} · ${a.role}`}))}/></Field><Field label="CLI и модель новой попытки"><ProviderModelPicker value={selection} onChange={setSelection} routing={agent?.hostId?{kind:'host',hostId:agent.hostId}:undefined} allowProviderChange align="start"/></Field><TextField label="Что продолжить или изменить" value={reason} onChange={setReason} multiline/><p className="text-xs text-muted-foreground">Передаются описание, критерии и {files.length} файлов с версиями. Проект остаётся «{job.project}». Изменения сохраняются до перезагрузки; реальные процессы не запускаются и не останавливаются.</p></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Отмена</Button><Button disabled={!agent||!agent.enabled||!reason.trim()} onClick={submit}>Сохранить передачу в примере</Button></DialogFooter></DialogContent></Dialog></>;
}
