import { useState } from 'react';
import type { Agent, Job } from './data';
import { AgentMark, Button, PageHead, TabBar, Status, Empty } from './shared';
export function InboxPage({jobs,agents,readIds,setReadIds,go}:{jobs:Job[];agents:Agent[];readIds:string[];setReadIds:(ids:string[])=>void;go:(s:string,id?:string)=>void}) {
 const [tab,setTab]=useState('Нужно ваше решение');
 const decisions=jobs.filter(j=>j.state==='blocked'||j.state==='review');
 const updates=jobs.filter(j=>j.state==='done');
 const list=tab==='Нужно ваше решение'?decisions:updates;
 return <div className="space-y-5"><PageHead title="Входящие" description="Здесь собраны задачи, где нужен ваш ответ или проверка результата."/><TabBar value={tab} onChange={setTab} tabs={['Нужно ваше решение','Уведомления']}/>
 <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-muted-foreground">{tab==='Нужно ваше решение'?`${decisions.length} задач ждут решения. Просмотр не закрывает запрос.`:`${updates.filter(j=>!readIds.includes(j.id)).length} непрочитанных. Полная история остаётся в задачах.`}</p>{tab==='Уведомления'&&<Button size="sm" variant="outline" disabled={updates.every(j=>readIds.includes(j.id))} onClick={()=>setReadIds([...new Set([...readIds,...updates.map(j=>j.id)])])}>Отметить все прочитанными</Button>}</div>
 {!list.length?<Empty title={tab==='Нужно ваше решение'?'Ваших решений сейчас не требуется':'Новых уведомлений нет'} description="Можно продолжить работу со списком задач."/>:<div className="max-w-4xl divide-y divide-border rounded-lg border border-border">{list.map(j=><div key={j.id} className="grid grid-cols-[36px_minmax(0,1fr)] items-start gap-3 p-4 sm:grid-cols-[36px_minmax(0,1fr)_auto]"><span className="flex size-9 shrink-0 items-center justify-center rounded-full border border-border bg-muted"><AgentMark id={agents.find(a=>a.name===j.agent)?.selection.providerId||''}/></span><div className="min-w-0 flex-1"><button className="text-left text-sm font-medium hover:underline" onClick={()=>go('jobs',j.id)}>{j.title}</button><p className="mt-1 text-xs text-muted-foreground">{j.id} · {j.project} · {j.agent}</p><p className="mt-2 text-sm">{j.state==='blocked'?'Уточните вводные, чтобы исполнитель мог продолжить.':j.state==='review'?'Откройте результат и примите его или верните с замечаниями.':'Работа завершена; результат и обсуждение доступны в задаче.'}</p></div><div className="col-start-2 flex flex-wrap items-center gap-2 sm:col-start-3 sm:flex-col sm:items-end"><Status state={j.state}/><Button size="sm" variant="outline" onClick={()=>{if(tab==='Уведомления')setReadIds([...new Set([...readIds,j.id])]);go('jobs',j.id);}}>{j.state==='review'?'Проверить результат':j.state==='blocked'?'Открыть запрос':'Открыть задачу'}</Button>{tab==='Уведомления'&&<span className="text-xs text-muted-foreground">{readIds.includes(j.id)?'Прочитано':'Новое'}</span>}</div></div>)}</div>}
 </div>;
}
