import { useState } from "react";
import { Markdown } from "@get-bb/plugin-sdk/app";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "../../../components/ui/dialog";
import { type Job, type State, states, stateNames } from "./data";
import { Button, Icon, TextField, Choice, Status, Field } from "./shared";

type Props = {job:Job;jobs:Job[];update:(j:Job)=>void;addJob:(j:Job)=>void;openJob:(id:string)=>void;back:()=>void;notice:(s:string)=>void;openRun:()=>void};
const nextState: Partial<Record<State, string>> = {
 backlog:"Поручение ещё не отправлено исполнителю.",queued:"Поручение в очереди. Ожидаем исполнителя.",
 running:"Исполнитель готовит результат.",review:"Результат ожидает проверки.",blocked:"Нужно уточнить вводные перед продолжением.",done:"Результат принят.",canceled:"Работа отменена.",
};
export function JobDetail({job,jobs,update,addJob,openJob,back,notice,openRun}:Props) {
 const [comment,setComment]=useState("");const [filter,setFilter]=useState("all");
 const [editing,setEditing]=useState(false);const [title,setTitle]=useState(job.title);const [description,setDescription]=useState(job.description);
 const [childForm,setChildForm]=useState(false);const [childTitle,setChildTitle]=useState("");
 const [preview,setPreview]=useState(false);const [reviewing,setReviewing]=useState(false);const [reason,setReason]=useState("");
 const children=jobs.filter(j=>j.parentId===job.id);const parent=jobs.find(j=>j.id===job.parentId);
 const hasExample=job.id==="AG-102";
 const change=(patch:Partial<Job>,text:string)=>update({...job,...patch,activity:[...(job.activity||[]),{id:crypto.randomUUID(),kind:"event",text,at:new Date().toISOString()}]});
 const setStatus=(state:State)=>{if(state!==job.state)change({state},`Вы изменили статус: ${stateNames[job.state]} → ${stateNames[state]}`);};
 const activity=[...job.comments.map((text,i)=>({id:`initial-${i}`,kind:"comment" as const,text,at:""})),...(job.activity||[])].filter(x=>filter==="all"||x.kind===filter);
 const submitComment=()=>{if(!comment.trim())return;update({...job,activity:[...(job.activity||[]),{id:crypto.randomUUID(),kind:"comment",text:`Вы: ${comment.trim()}`,at:new Date().toISOString()}]});setComment("");};
 const createChild=()=>{if(!childTitle.trim())return;const id=`AG-${Math.max(100,...jobs.map(j=>Number(j.id.slice(3))))+1}`;addJob({id,title:childTitle.trim(),parentId:job.id,state:"backlog",project:job.project,department:job.department,agent:job.agent,priority:"Обычный",due:job.due,description:"Опишите ожидаемый результат и критерии приёмки.",comments:[]});setChildTitle("");setChildForm(false);};
 return <article className="mx-auto w-full max-w-4xl px-1 pb-8 sm:px-4">
  <nav aria-label="Путь задачи" className="mb-5 flex flex-wrap items-center gap-1 text-xs text-muted-foreground"><Button size="sm" variant="ghost" onClick={back}>Все задачи</Button><span>/</span>{parent&&<><Button size="sm" variant="ghost" onClick={()=>openJob(parent.id)}>{parent.id}</Button><span>/</span></>}<span className="px-2 font-mono">{job.id}</span></nav>
  <header className="space-y-4 border-b border-border pb-5"><div className="flex items-start justify-between gap-3"><h1 className="min-w-0 break-words text-xl font-semibold leading-snug tracking-tight">{job.title}</h1><Button size="sm" variant="ghost" onClick={()=>{setTitle(job.title);setDescription(job.description);setEditing(true);}}>Редактировать</Button></div>
   <div className="grid grid-cols-2 gap-3 text-xs sm:grid-cols-3 [&_button[role=combobox]]:h-8 [&_button[role=combobox]]:text-xs">
    <Field label="Статус"><Choice label="Статус задачи" value={job.state} onChange={v=>setStatus(v as State)} options={states.map(value=>({value,label:stateNames[value]}))}/></Field>
    <Field label="Исполнитель"><Choice label="Исполнитель задачи" value={job.agent} onChange={agent=>change({agent},`Исполнитель: ${agent}`)} options={["Мария","Анна","Марк","Илья","София"]}/></Field>
    <Field label="Приоритет"><Choice label="Приоритет задачи" value={job.priority} onChange={priority=>change({priority},`Приоритет: ${priority}`)} options={["Низкий","Обычный","Высокий","Срочный"]}/></Field>
   </div>
   <details className="text-xs"><summary className="cursor-pointer text-muted-foreground focus-visible:outline focus-visible:outline-ring">{job.project} · {job.department} · Срок: {job.due || "не задан"}</summary><div className="mt-3 grid gap-3 sm:grid-cols-3"><Field label="Проект"><Choice label="Проект задачи" value={job.project} onChange={project=>change({project},`Проект: ${project}`)} options={["SelfyStudio","BB-сервис"]}/></Field><Field label="Отдел"><Choice label="Отдел задачи" value={job.department} onChange={department=>change({department},`Отдел: ${department}`)} options={["Маркетинг","Редакция","Дизайн","Исследования"]}/></Field><TextField label="Срок" type="date" value={job.due} onChange={due=>change({due},`Срок: ${due || "не задан"}`)}/></div></details>
  </header>
  <section aria-label="Текущее состояние" className="flex flex-wrap items-center justify-between gap-3 border-b border-border py-4"><div><div className="mb-1 flex items-center gap-2"><h2 className="text-sm font-medium">Сейчас</h2><Status state={job.state}/></div><p className="text-sm text-muted-foreground">{nextState[job.state]} {job.state==="running"?job.agent:""}</p></div>{job.state==="backlog"&&<Button size="sm" onClick={()=>setStatus("queued")}>Передать в работу</Button>}{job.state==="blocked"&&<span className="text-xs text-muted-foreground">Вопросы исполнителя появятся в истории.</span>}</section>
  {hasExample&&<section className="border-b border-border py-5" aria-label="Результат"><div className="mb-3 flex items-center justify-between gap-2"><h2 className="text-sm font-medium">Результат</h2><span className="text-xs text-muted-foreground">Демонстрационный материал</span></div><div className="flex flex-wrap items-center justify-between gap-3 rounded-md border border-border p-3"><button onClick={()=>setPreview(true)} className="flex items-center gap-3 text-left hover:underline focus-visible:outline focus-visible:outline-ring"><Icon name="Info" className="size-4"/><span className="text-sm">Оффер.md<span className="block text-xs text-muted-foreground">Версия 2 · Анна · пример текста</span></span></button>{job.state==="review"&&<div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>setReviewing(true)}>Вернуть</Button><Button size="sm" onClick={()=>change({state:"done"},"Вы приняли Оффер.md, версию 2")}>Принять результат</Button></div>}</div></section>}
  <section className="border-b border-border py-5"><h2 className="mb-3 text-sm font-medium">Описание и критерии</h2><div className="max-w-prose text-sm"><Markdown content={job.description}/></div></section>
  <section className="border-b border-border py-5"><div className="mb-3 flex items-center justify-between gap-2"><h2 className="text-sm font-medium">Подзадачи <span className="ml-1 text-xs text-muted-foreground">{children.filter(j=>j.state==="done").length}/{children.length}</span></h2><Button size="sm" variant="ghost" onClick={()=>setChildForm(true)}>Добавить подзадачу</Button></div>{children.length?children.map(child=><button key={child.id} onClick={()=>openJob(child.id)} className="flex min-h-10 w-full items-center gap-3 border-b border-border py-2 text-left text-sm hover:bg-muted/40 focus-visible:outline focus-visible:outline-ring"><span className="font-mono text-xs text-muted-foreground">{child.id}</span><span className="min-w-0 flex-1 truncate">{child.title}</span><Status state={child.state}/></button>):<p className="text-xs text-muted-foreground">Подзадач пока нет. Добавьте отдельный результат, который нужно поручить.</p>}</section>
  <section className="border-b border-border py-5"><h2 className="mb-3 text-sm font-medium">Исполнители и запуски</h2>{hasExample?<div className="flex items-center justify-between gap-3 text-sm"><div><span>Анна · Подготовка оффера</span><p className="mt-1 text-xs text-muted-foreground">RUN-204 · пример завершённого запуска</p></div><Button size="sm" variant="outline" onClick={openRun}>Открыть запуск</Button></div>:<p className="text-xs text-muted-foreground">Запусков нет. Назначенный исполнитель — {job.agent}.</p>}</section>
  <section className="pt-5" aria-label="История задачи"><div className="mb-4 flex items-center justify-between gap-3"><h2 className="text-sm font-medium">История и обсуждение</h2><div className="w-40"><Choice label="Фильтр истории" value={filter} onChange={setFilter} options={[{value:"all",label:"Всё"},{value:"comment",label:"Комментарии"},{value:"event",label:"События"}]}/></div></div>
   {activity.length?<ol className="ml-2 border-l border-border">{activity.map(item=><li key={item.id} className="relative mb-4 pl-5"><span className="absolute -left-1.5 top-1 size-3 rounded-full border border-border bg-background"/><div className="mb-1 flex gap-2 text-xs text-muted-foreground"><span>{item.kind==="comment"?"Комментарий":"Изменение"}</span><span>{item.at?<time dateTime={item.at}>{new Date(item.at).toLocaleTimeString("ru",{hour:"2-digit",minute:"2-digit"})}</time>:"Начало примера"}</span></div><p className={`whitespace-pre-wrap break-words ${item.kind==="event"?"text-xs text-muted-foreground":"text-sm"}`}>{item.text}</p></li>)}</ol>:<p className="mb-4 text-xs text-muted-foreground">Здесь пока нет {filter==="event"?"событий":"сообщений"}.</p>}
   <div className="mt-5 space-y-2"><TextField label="Комментарий к задаче" value={comment} onChange={setComment} multiline/><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-xs text-muted-foreground">Комментарий сохранится в примере. Агент не запускается.</span><Button size="sm" disabled={!comment.trim()} onClick={submitComment}>Добавить комментарий</Button></div></div>
  </section>
  <Dialog open={editing} onOpenChange={setEditing}><DialogContent><DialogHeader><DialogTitle>Редактировать задачу</DialogTitle><DialogDescription>Изменения сохранятся в примере до перезагрузки страницы.</DialogDescription></DialogHeader><TextField label="Название" value={title} onChange={setTitle}/><TextField label="Описание и критерии" value={description} onChange={setDescription} multiline/><DialogFooter><Button variant="outline" onClick={()=>setEditing(false)}>Отмена</Button><Button disabled={!title.trim()} onClick={()=>{change({title:title.trim(),description},"Вы обновили описание задачи");setEditing(false);}}>Сохранить</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={childForm} onOpenChange={setChildForm}><DialogContent><DialogHeader><DialogTitle>Новая подзадача</DialogTitle><DialogDescription>Будет связана с {job.id} и унаследует проект и исполнителя.</DialogDescription></DialogHeader><TextField label="Название подзадачи" value={childTitle} onChange={setChildTitle}/><DialogFooter><Button variant="outline" onClick={()=>setChildForm(false)}>Отмена</Button><Button disabled={!childTitle.trim()} onClick={createChild}>Создать подзадачу</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={preview} onOpenChange={setPreview}><DialogContent><DialogHeader><DialogTitle>Оффер.md · версия 2</DialogTitle><DialogDescription>Демонстрационный текст, не реальный файл.</DialogDescription></DialogHeader><Markdown content={"## AI-фотосессия для вашего профиля\n\nПодберите образ и подготовьте фотографии для личной страницы.\n\n_Перед публикацией проверить фактические условия услуги и согласовать формулировки._"}/></DialogContent></Dialog>
  <Dialog open={reviewing} onOpenChange={setReviewing}><DialogContent><DialogHeader><DialogTitle>Вернуть версию 2 на доработку</DialogTitle><DialogDescription>Укажите, что требуется изменить в результате.</DialogDescription></DialogHeader><TextField label="Замечания" value={reason} onChange={setReason} multiline/><DialogFooter><Button variant="outline" onClick={()=>setReviewing(false)}>Отмена</Button><Button disabled={!reason.trim()} onClick={()=>{change({state:"running"},`Вы вернули Оффер.md, версию 2: ${reason.trim()}`);setReason("");setReviewing(false);}}>Вернуть на доработку</Button></DialogFooter></DialogContent></Dialog>
 </article>;
}
