import { useState } from "react";
import { Markdown } from "@get-bb/plugin-sdk/app";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "../../../components/ui/dialog";
import { Table, TableHeader, TableHead, TableBody, TableRow, TableCell } from "../../../components/ui/table";
import { type Job, type State, states, stateNames } from "./data";
import { Button, Input, TextField, Choice, PageHead, TabBar, Panel, Status, Empty, Rows } from "./shared";

export function JobsPage({ jobs, setJobs, open, project, department }: { jobs: Job[]; setJobs: (j: Job[]) => void; open: (id: string) => void; project?: string; department?: string }) {
 const [view,setView]=useState("Канбан");const [q,setQ]=useState("");const [filter,setFilter]=useState("all");const [pr,setPr]=useState("all");const [form,setForm]=useState(false);const [title,setTitle]=useState("");
 const filtered=jobs.filter(j=>(!project||j.project===project)&&(!department||j.department===department)&&(pr==="all"||j.project===pr)&&(filter==="all"||j.state===filter)&&(j.title+" "+j.id).toLowerCase().includes(q.toLowerCase()));
 const move=(id:string,state:State)=>setJobs(jobs.map(j=>j.id===id?{...j,state}:j));
 const create=()=>{if(!title.trim())return;const id=`AG-${Math.max(...jobs.map(j=>Number(j.id.slice(3))),100)+1}`;setJobs([...jobs,{id,title:title.trim(),state:"backlog",project:project||"SelfyStudio",department:department||"Маркетинг",agent:"Мария",priority:"Обычный",due:"2026-09-18",description:"Добавьте вводные и критерии приёмки.",comments:[]}]);setForm(false);setTitle("");open(id);};
 return <div className="space-y-5"><PageHead title={project||department?"Очередь задач":"Задачи"} description="Одна очередь — по проектам, отделам и сотрудникам."><Button onClick={()=>setForm(true)}>Создать задачу</Button></PageHead>
 <div className="flex flex-wrap gap-2"><div className="min-w-48 flex-1"><Input aria-label="Поиск задач" placeholder="Поиск по названию или номеру…" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="w-44"><Choice label="Фильтр статуса" value={filter} onChange={setFilter} options={[{value:"all",label:"Все статусы"},...states.map(s=>({value:s,label:stateNames[s]}))]}/></div>{!project&&<div className="w-44"><Choice label="Фильтр проекта" value={pr} onChange={setPr} options={[{value:"all",label:"Все проекты"},"SelfyStudio","BB-сервис"]}/></div>}<TabBar value={view} onChange={setView} tabs={["Канбан","Список"]}/></div>
 {filtered.length===0?<Empty title="Задачи не найдены" description="Измените фильтры или создайте новое поручение."/>:view==="Канбан"?<div className="flex gap-3 overflow-x-auto pb-3" aria-label="Канбан задач">{states.filter(s=>filter==="all"||filter===s).map(s=><section key={s} aria-label={stateNames[s]} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();move(e.dataTransfer.getData("text/plain"),s);}} className="w-64 shrink-0 rounded-lg bg-muted/40 p-2"><div className="mb-3 flex items-center justify-between px-1 py-1"><Status state={s}/><span className="text-xs text-muted-foreground">{filtered.filter(j=>j.state===s).length}</span></div><div className="space-y-2">{filtered.filter(j=>j.state===s).map(j=><button key={j.id} draggable onDragStart={e=>e.dataTransfer.setData("text/plain",j.id)} onClick={()=>open(j.id)} className="w-full rounded-md border border-border bg-card p-3 text-left shadow-sm hover:border-ring focus-visible:outline focus-visible:outline-2 focus-visible:outline-ring"><span className="text-xs text-muted-foreground">{j.id} · {j.priority}</span><p className="my-2 text-sm font-medium leading-5">{j.title}</p><p className="text-xs text-muted-foreground">{j.project}</p><div className="mt-3 flex justify-between text-xs"><span>{j.agent}</span><span>{j.due.slice(5)}</span></div></button>)}</div></section>)}</div>:<div className="overflow-x-auto rounded-lg border border-border"><Table><TableHeader><TableRow><TableHead>Задача</TableHead><TableHead>Статус</TableHead><TableHead>Проект / отдел</TableHead><TableHead>Исполнитель</TableHead><TableHead>Срок</TableHead></TableRow></TableHeader><TableBody>{filtered.map(j=><TableRow key={j.id}><TableCell><button className="text-left hover:underline" onClick={()=>open(j.id)}><span className="mr-2 text-xs text-muted-foreground">{j.id}</span>{j.title}</button></TableCell><TableCell><Status state={j.state}/></TableCell><TableCell>{j.project}<p className="text-xs text-muted-foreground">{j.department}</p></TableCell><TableCell>{j.agent}</TableCell><TableCell>{j.due}</TableCell></TableRow>)}</TableBody></Table></div>}
 <p className="text-xs text-muted-foreground">Карточки можно переносить между колонками. Смена статуса также доступна внутри задачи.</p>
 <Dialog open={form} onOpenChange={setForm}><DialogContent><DialogHeader><DialogTitle>Новая задача</DialogTitle><DialogDescription>Создаётся только в примере интерфейса.</DialogDescription></DialogHeader><TextField label="Название задачи" value={title} onChange={setTitle}/><DialogFooter><Button variant="outline" onClick={()=>setForm(false)}>Отмена</Button><Button disabled={!title.trim()} onClick={create}>Создать</Button></DialogFooter></DialogContent></Dialog>
 </div>;
}
export function JobDetail({ job, update, back, notice, openRun }: { job:Job;update:(j:Job)=>void;back:()=>void;notice:(s:string)=>void;openRun:()=>void }) {
 const [tab,setTab]=useState("Описание");const [comment,setComment]=useState("");const [edit,setEdit]=useState(false);
 return <div className="space-y-5"><Button variant="ghost" size="sm" onClick={back}>← Все задачи</Button><PageHead title={`${job.id} · ${job.title}`}><Button variant="outline" onClick={()=>setEdit(!edit)}>{edit?"Закончить правку":"Редактировать"}</Button><Button onClick={()=>{update({...job,state:"queued"});notice("В примере задача передана в очередь. Реальный агент не запущен.");}}>Передать в работу</Button></PageHead>
 <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_260px]"><main className="min-w-0 space-y-4"><TabBar value={tab} onChange={setTab} tabs={["Описание","Подзадачи","Результаты","Запуски","История"]}/>
 {tab==="Описание"&&<><Panel>{edit?<><TextField label="Название" value={job.title} onChange={title=>update({...job,title})}/><TextField label="Описание и приёмка" multiline value={job.description} onChange={description=>update({...job,description})}/></>:<Markdown content={job.description}/>}</Panel><Panel title="Обсуждение">{job.comments.map((c,i)=><p key={i} className="mb-3 border-b border-border pb-3 text-sm">{c}</p>)}<TextField label="Комментарий" value={comment} onChange={setComment} multiline/><Button className="mt-2" disabled={!comment.trim()} onClick={()=>{update({...job,comments:[...job.comments,`Вы: ${comment}`]});setComment("");}}>Добавить комментарий</Button></Panel></>}
 {tab==="Подзадачи"&&<Panel title="Состав и зависимости"><Rows rows={[["Исследование аудитории",<Status state="done"/>],["Текст оффера",<Status state="review"/>],["Дизайн",<Status state="queued"/>]]}/><Button variant="outline" onClick={()=>notice("В полном продукте здесь создаётся связанная задача с тем же проектом и владельцем приёмки.")}>Добавить подзадачу</Button></Panel>}
 {tab==="Результаты"&&<Panel title="Материалы для проверки"><Rows rows={[["Оффер.md",<span>Версия 2 · пример</span>],["Проверяющий","Марк"],["Критерий","Все факты подтверждены"]]}/><div className="mt-3 flex flex-wrap gap-2"><Button onClick={()=>{update({...job,state:"done"});notice("Версия принята в прототипе.");}}>Принять результат</Button><Button variant="outline" onClick={()=>{update({...job,state:"running"});notice("В примере результат возвращён на доработку.");}}>Вернуть на доработку</Button><Button variant="outline" onClick={()=>notice("Файлы будут открываться через штатный FileLink BB. У демонстрационного результата нет файла.")}>Открыть материал</Button></div></Panel>}
 {tab==="Запуски"&&<Panel title="Исполнения этой задачи"><Rows rows={[["RUN-204 · Анна","Результат передан"],["RUN-205 · Марк","Ожидает запуска"]]}/><Button variant="outline" onClick={openRun}>Посмотреть запуск</Button></Panel>}
 {tab==="История"&&<Panel title="История примера"><Rows rows={[["10:00 · Мария","Создала поручение"],["10:02 · Анна","Взяла в работу"],["10:18 · Анна","Передала результат v2"],["10:18 · Правило","Назначило проверку"]]}/></Panel>}
 </main><aside className="space-y-4"><Panel title="Свойства"><div className="space-y-4"><Choice label="Статус задачи" value={job.state} onChange={state=>update({...job,state:state as State})} options={states.map(s=>({value:s,label:stateNames[s]}))}/><Choice label="Проект задачи" value={job.project} onChange={project=>update({...job,project})} options={["SelfyStudio","BB-сервис"]}/><Choice label="Отдел задачи" value={job.department} onChange={department=>update({...job,department})} options={["Маркетинг","Редакция","Дизайн","Исследования"]}/><Choice label="Исполнитель задачи" value={job.agent} onChange={agent=>update({...job,agent})} options={["Мария","Анна","Марк","Илья","София"]}/><Choice label="Приоритет задачи" value={job.priority} onChange={priority=>update({...job,priority})} options={["Низкий","Обычный","Высокий","Срочный"]}/><TextField label="Срок" type="date" value={job.due} onChange={due=>update({...job,due})}/></div></Panel><p className="text-xs text-muted-foreground">Изменения действуют только в прототипе.</p></aside></div></div>;
}
