import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "../../../components/ui/dialog";
import { type Job, type State, states, stateNames } from "./data";
import { Button, Icon, Input, TextField, Choice, PageHead, TabBar, Panel, Status, Empty, Rows } from "./shared";

export function JobsPage({ jobs, setJobs, open, project, department }: { jobs: Job[]; setJobs: (j: Job[]) => void; open: (id: string) => void; project?: string; department?: string }) {
 const [view,setView]=useState("Список");const [q,setQ]=useState("");const [filter,setFilter]=useState("all");const [pr,setPr]=useState("all");const [form,setForm]=useState(false);const [title,setTitle]=useState("");
 const [priority,setPriority]=useState("all");const [sort,setSort]=useState("id");
 const filtered=jobs.filter(j=>(!project||j.project===project)&&(!department||j.department===department)&&(pr==="all"||j.project===pr)&&(priority==="all"||j.priority===priority)&&(filter==="all"||j.state===filter)&&(j.title+" "+j.id).toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==="due"?a.due.localeCompare(b.due):a.id.localeCompare(b.id));
 const move=(id:string,state:State)=>setJobs(jobs.map(j=>j.id===id?{...j,state}:j));
 const create=()=>{if(!title.trim())return;const id=`AG-${Math.max(...jobs.map(j=>Number(j.id.slice(3))),100)+1}`;setJobs([...jobs,{id,title:title.trim(),state:"backlog",project:project||"SelfyStudio",department:department||"Маркетинг",agent:"Мария",priority:"Обычный",due:"2026-09-18",description:"Добавьте вводные и критерии приёмки.",comments:[]}]);setForm(false);setTitle("");open(id);};
 return <div className="space-y-3"><PageHead title={project||department?"Очередь задач":"Задачи"}><Button size="sm" onClick={()=>setForm(true)}><Icon name="Plus" className="mr-1 size-3.5"/>Новая задача</Button></PageHead>
 <div className="flex flex-wrap items-center gap-2 border-b border-border pb-3 [&_button[role=combobox]]:h-7 [&_button[role=combobox]]:border-dashed [&_button[role=combobox]]:px-2 [&_button[role=combobox]]:text-xs"><div className="w-32"><Choice label="Фильтр статуса" value={filter} onChange={setFilter} options={[{value:"all",label:"Статус"},...states.map(s=>({value:s,label:stateNames[s]}))]}/></div><div className="w-32"><Choice label="Приоритет" value={priority} onChange={setPriority} options={[{value:"all",label:"Приоритет"},"Низкий","Обычный","Высокий","Срочный"]}/></div>{!project&&<div className="w-32"><Choice label="Фильтр проекта" value={pr} onChange={setPr} options={[{value:"all",label:"Проект"},"SelfyStudio","BB-сервис"]}/></div>}<Input className="h-7 w-40 border-transparent bg-transparent text-xs shadow-none" aria-label="Поиск задач" placeholder="Поиск задач…" value={q} onChange={e=>setQ(e.target.value)}/><div className="ml-auto flex items-center gap-2"><div className="w-28"><Choice label="Сортировка" value={sort} onChange={setSort} options={[{value:"id",label:"По номеру"},{value:"due",label:"По сроку"}]}/></div><span className="whitespace-nowrap text-xs text-muted-foreground">{filtered.length} задач</span><TabBar value={view} onChange={setView} tabs={["Список","Канбан"]}/></div></div>
 {filtered.length===0?<Empty title="Задачи не найдены" description="Измените фильтры или создайте новое поручение."/>:view==="Канбан"?<div className="flex gap-3 overflow-x-auto pb-3" aria-label="Канбан задач">{states.filter(s=>filter==="all"||filter===s).map(s=><section key={s} aria-label={stateNames[s]} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();move(e.dataTransfer.getData("text/plain"),s);}} className="w-60 shrink-0 bg-muted/20 p-2"><div className="mb-3 flex items-center justify-between px-1 py-1"><Status state={s}/><span className="text-xs text-muted-foreground">{filtered.filter(j=>j.state===s).length}</span></div><div className="space-y-2">{filtered.filter(j=>j.state===s).map(j=><button key={j.id} draggable onDragStart={e=>e.dataTransfer.setData("text/plain",j.id)} onClick={()=>open(j.id)} className="w-full rounded-md border border-border bg-card p-2.5 text-left hover:border-ring focus-visible:outline focus-visible:outline-2 focus-visible:outline-ring"><span className="text-xs text-muted-foreground">{j.id} · {j.priority}</span><p className="my-1.5 text-sm leading-5">{j.title}</p><p className="text-xs text-muted-foreground">{j.project}</p><div className="mt-2 flex justify-between text-xs"><span>{j.agent}</span><span>{j.due.slice(5)}</span></div></button>)}</div></section>)}</div>:<div aria-label="Список задач по статусам" className="-mx-3 md:-mx-4">{states.filter(state=>filtered.some(j=>j.state===state)).map(state=><section key={state} aria-label={stateNames[state]}><div className="flex h-9 items-center gap-2 border-b border-border bg-muted/30 px-4 font-medium"><Status state={state}/><span className="text-xs text-muted-foreground">{filtered.filter(j=>j.state===state).length}</span></div>{filtered.filter(j=>j.state===state).map(j=><button key={j.id} onClick={()=>open(j.id)} className="flex min-h-9 w-full items-center gap-3 border-b border-border px-4 py-2 text-left text-sm hover:bg-muted/50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-ring"><span title={j.priority} aria-label={`Приоритет: ${j.priority}`} className={j.priority==="Высокий"||j.priority==="Срочный"?"text-foreground":"text-muted-foreground/40"}><Icon name="ArrowUp" className="size-3"/></span><span className="w-14 shrink-0 font-mono text-xs text-muted-foreground">{j.id}</span><span className="min-w-0 flex-1 truncate">{j.title}</span><span className="hidden text-xs text-muted-foreground xl:block">{j.project}</span><span className="hidden w-14 truncate text-right text-xs text-muted-foreground sm:block">{j.agent}</span>{j.state==="running"&&<span className="rounded border border-border px-1.5 text-[10px] text-muted-foreground">В работе</span>}<span title={j.department} className="size-2 shrink-0 rounded-full bg-blue-500"/></button>)}</section>)}</div>}

 <Dialog open={form} onOpenChange={setForm}><DialogContent><DialogHeader><DialogTitle>Новая задача</DialogTitle><DialogDescription>Создаётся только в примере интерфейса.</DialogDescription></DialogHeader><TextField label="Название задачи" value={title} onChange={setTitle}/><DialogFooter><Button variant="outline" onClick={()=>setForm(false)}>Отмена</Button><Button disabled={!title.trim()} onClick={create}>Создать</Button></DialogFooter></DialogContent></Dialog>
 </div>;
}
export { JobDetail } from "./job-detail";
