import { useState } from 'react';
import { Markdown } from '@get-bb/plugin-sdk/app';
import { Button, TextField, Field, Choice, PageHead, SearchInput, Empty, Collection } from './shared';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '../../../components/ui/dialog';
export interface Material { id:string; title:string; scope:string; source:string; body:string; status:'accepted'|'proposal'; }
export const seedMaterials:Material[] = [
 {id:'project',title:'Правила SelfyStudio',scope:'SelfyStudio',source:'Решение владельца · пример',body:'Объясняем услугу простым языком. Не обещаем результат без подтверждения.',status:'accepted'},
 {id:'department',title:'Порядок работы редакции',scope:'Редакция',source:'Правила отдела · пример',body:'Бриф → текст → проверка → исправления. Каждое утверждение опирается на источник.',status:'accepted'},
 {id:'proposal',title:'Уточнить сегмент аудитории',scope:'SelfyStudio',source:'Предложение исследователя · пример',body:'Уточнить сегмент аудитории для нового оффера. Нужна проверка перед включением в правила проекта.',status:'proposal'},
];
export function KnowledgePage({items,setItems,scopes}:{items:Material[];setItems:(items:Material[])=>void;scopes:string[]}) {
 const [q,setQ]=useState('');const [scope,setScope]=useState('all');const [status,setStatus]=useState('all');
 const [selected,setSelected]=useState<string|null>(null);const [draft,setDraft]=useState<Material|null>(null);
 const current=items.find(i=>i.id===selected);
 const visible=items.filter(i=>(scope==='all'||i.scope===scope)&&(status==='all'||i.status===status)&&(i.title+' '+i.body+' '+i.source).toLowerCase().includes(q.toLowerCase()));
 const scopeOptions=[...new Set([...scopes,...items.map(i=>i.scope)])];
 const save=()=>{if(!draft?.title.trim()||!draft.body.trim()||!draft.source.trim())return;const saved={...draft,status:"proposal" as const};setItems(items.some(i=>i.id===saved.id)?items.map(i=>i.id===saved.id?saved:i):[...items,saved]);setSelected(saved.id);setDraft(null);};
 return <div className="space-y-5"><PageHead title="Знания" description="Материалы и принятые правила. Предложения ждут проверки перед использованием."><Button onClick={()=>setDraft({id:crypto.randomUUID(),title:'',scope:scope==='all'?scopeOptions[0]||'Агентство':scope,source:'',body:'',status:'proposal'})}>Добавить материал</Button></PageHead>
 <div className="flex flex-wrap gap-2"><SearchInput aria-label="Поиск знаний" placeholder="Найти материал или источник…" value={q} onChange={e=>setQ(e.target.value)}/><div className="w-44"><Choice label="Область знаний" value={scope} onChange={setScope} options={[{value:'all',label:'Все проекты и отделы'},...scopeOptions]}/></div><div className="w-44"><Choice label="Статус материала" value={status} onChange={setStatus} options={[{value:'all',label:'Все материалы'},{value:'accepted',label:'Принятые'},{value:'proposal',label:'Предложения'}]}/></div></div>
 <Collection columns={['Материал','Состояние','Область','Источник']} rows={visible.map(i=>({id:i.id,name:<span className="font-medium">{i.title}</span>,cells:[i.status==='accepted'?'Принят':'На проверке',i.scope,i.source],open:()=>setSelected(i.id)}))}/>
 {current&&<section className="max-w-3xl rounded-lg border border-border bg-muted/20 p-5"><div className="mb-3 flex flex-wrap items-start justify-between gap-2"><div><h2 className="text-base font-semibold">{current.title}</h2><p className="mt-1 text-xs text-muted-foreground">{current.scope} · {current.source}</p></div><Button size="sm" variant="ghost" aria-label="Закрыть материал" onClick={()=>setSelected(null)}>Закрыть</Button></div><Markdown content={current.body}/><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setDraft({...current})}>Редактировать</Button>{current.status==='proposal'?<Button onClick={()=>setItems(items.map(i=>i.id===current.id?{...i,status:'accepted'}:i))}>Принять материал</Button>:<span className="self-center text-xs text-muted-foreground">Принят в текущем примере</span>}</div></section>}
 <Dialog open={Boolean(draft)} onOpenChange={open=>{if(!open)setDraft(null);}}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{items.some(i=>i.id===draft?.id)?'Изменить материал':'Новый материал'}</DialogTitle><DialogDescription>Укажите, где применяются сведения и откуда они получены. Новый материал сначала попадёт в предложения.</DialogDescription></DialogHeader>{draft&&<><TextField label="Название материала" value={draft.title} onChange={title=>setDraft({...draft,title})}/><Field label="Проект или отдел"><Choice label="Область материала" value={draft.scope} onChange={scope=>setDraft({...draft,scope})} options={scopeOptions}/></Field><TextField label="Источник — ссылка или документ" value={draft.source} onChange={source=>setDraft({...draft,source})}/><TextField label="Содержание материала" multiline value={draft.body} onChange={body=>setDraft({...draft,body})}/></>}<DialogFooter><Button variant="outline" onClick={()=>setDraft(null)}>Отмена</Button><Button disabled={!draft?.title.trim()||!draft.body.trim()||!draft.source.trim()} onClick={save}>Сохранить материал</Button></DialogFooter></DialogContent></Dialog>
 </div>;
}
