import { CustomMcpEditor } from "./custom-mcp";
import { SearchInput } from "./shared";
import { useState } from "react";
import { experimental_ProviderIcon as ProviderIcon, experimental_ProviderModelPicker as ProviderModelPicker, experimental_PermissionModePicker as PermissionModePicker, experimental_NewThreadComposer as NewThreadComposer } from "@get-bb/plugin-sdk/app";
import { Switch } from "../../../components/ui/switch";
import { type Agent, type Group, type Job, skillOptions, mcpOptions } from "./data";
import { Button, AgentMark, Input, TextField, Field, Choice, PageHead, TabBar, Panel, Checks, Rows, Empty, Collection, Icon } from "./shared";
import { JobsPage } from "./jobs";
import { OrgChart } from "./org-chart";

export function AgentsPage({ agents, open, create }: {agents:Agent[];open:(id:string)=>void;create:()=>void}) {
 const [q,setQ]=useState("");const [dep,setDep]=useState("all");
 const filtered=agents.filter(a=>(a.name+" "+a.role).toLowerCase().includes(q.toLowerCase())&&(dep==="all"||a.department===dep));
 return <div className="space-y-4"><PageHead title="Сотрудники" description="Кто выполняет работу и какие возможности ему доступны."><Button onClick={create}>Создать сотрудника</Button></PageHead><div className="flex flex-wrap items-center gap-2"><SearchInput className="max-w-xs" aria-label="Поиск сотрудников" placeholder="Найти по имени или роли…" value={q} onChange={e=>setQ(e.target.value)}/><div className="w-44"><Choice label="Отдел сотрудника" value={dep} onChange={setDep} options={[{value:"all",label:"Все отделы"},...new Set(agents.map(a=>a.department))]}/></div><span className="ml-auto text-xs text-muted-foreground">{filtered.length} сотрудников</span></div><Collection columns={["Сотрудник","Состояние","Отдел","Возможности","CLI"]} rows={filtered.map(a=>({id:a.id,open:()=>open(a.id),name:<span className="flex items-center gap-3"><span className="flex size-8 shrink-0 items-center justify-center rounded-full border border-border bg-muted"><AgentMark id={a.selection.providerId} className="size-5"/></span><span><span className="block font-medium">{a.name}</span><span className="block text-xs text-muted-foreground">{a.role}</span></span></span>,cells:[a.enabled?"Профиль включён":"На паузе",a.department,`Навыки: ${a.skills.length} · MCP: ${a.mcps.length+(a.customMcps?.filter(m=>m.enabled).length||0)}`,a.selection.providerId]}))}/></div>;

}
export function AgentDetail({ agent, update, hosts, back, notice }: {agent:Agent;update:(a:Agent)=>void;hosts:{id:string;name:string}[];back:()=>void;notice:(s:string)=>void}) {
 const [tab,setTab]=useState("Обзор");const [q,setQ]=useState("");const shell=agent.shell||false;const setShell=(shell:boolean)=>update({...agent,shell});const delegate=agent.delegate||false;const setDelegate=(delegate:boolean)=>update({...agent,delegate});
 const hostId=agent.hostId||hosts.find(h=>/mini/i.test(h.name))?.id||hosts[0]?.id;const routing=hostId?{kind:"host" as const,hostId}:undefined;
 return <div className="space-y-5"><Button variant="ghost" size="sm" onClick={back}>← Сотрудники</Button><PageHead title={agent.name} description={agent.role}><Button variant="outline" onClick={()=>update({...agent,enabled:!agent.enabled})}>{agent.enabled?"Приостановить":"Активировать"}</Button><Button onClick={()=>notice("Профиль сохранён в текущем прототипе. Настройки исполнения не применяются.")}>Сохранить профиль</Button></PageHead><TabBar value={tab} onChange={v=>{setTab(v);setQ("");}} tabs={["Обзор","Инструкции","Исполнение","Возможности","История"]}/>
 <div className="max-w-4xl space-y-4">
 {tab==="Обзор"&&<><section className="rounded-xl border border-border bg-muted/30 p-5"><div className="flex items-center gap-3"><AgentMark id={agent.selection.providerId} className="size-8"/><div><h2 className="text-base font-semibold">{agent.role}</h2><p className="text-sm text-muted-foreground">{agent.department} · {agent.enabled?"Профиль включён":"На паузе"}</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">Исполнение</p><p className="mt-1 text-sm">{agent.selection.providerId}</p></div><div><p className="text-xs text-muted-foreground">Навыки</p><p className="mt-1 text-sm">{agent.skills.length} выбрано</p></div><div><p className="text-xs text-muted-foreground">Подключения</p><p className="mt-1 text-sm">{agent.mcps.length+(agent.customMcps?.filter(m=>m.enabled).length||0)} MCP</p></div></div></section><Panel title="Рабочий профиль"><div className="grid gap-4 md:grid-cols-2"><TextField label="Имя" value={agent.name} onChange={name=>update({...agent,name})}/><TextField label="Роль" value={agent.role} onChange={role=>update({...agent,role})}/><Field label="Отдел"><Choice label="Отдел" value={agent.department} onChange={department=>update({...agent,department})} options={["Маркетинг","Редакция","Дизайн","Исследования"]}/></Field><Field label="Статус"><Choice label="Статус сотрудника" value={agent.enabled?"active":"paused"} onChange={s=>update({...agent,enabled:s==="active"})} options={[{value:"active",label:"Профиль включён"},{value:"paused",label:"Приостановлен"}]}/></Field></div></Panel></>}
 {tab==="Инструкции"&&<><Panel title="Обязанности и порядок работы"><TextField label="Инструкции сотрудника" multiline value={agent.instructions} onChange={instructions=>update({...agent,instructions})}/></Panel><Panel title="Контекст на каждом запуске"><Rows rows={[["1. Проект","Факты, правила и принятые решения"],["2. Отдел","Процесс и критерии приёмки"],["3. Сотрудник","Эти инструкции и выбранные навыки"],["4. Задача","Поручение и версии материалов"]]}/></Panel></>}
 {tab==="Исполнение"&&<><Panel title="CLI и модель"><div className="space-y-5"><Field label="Машина" hint="Каталог машин считывается из BB. Выбор влияет только на черновик профиля.">{hosts.length?<Choice label="Машина сотрудника" value={hostId||""} onChange={hostId=>update({...agent,hostId})} options={hosts.map(h=>({value:h.id,label:h.name}))}/>:<p className="text-sm">Каталог машин пока недоступен.</p>}</Field><Field label="CLI / модель / reasoning / service tier" hint="Штатный выбор BB: возможности и модели берутся из актуального каталога."><ProviderModelPicker value={agent.selection} onChange={selection=>update({...agent,selection})} routing={routing} allowProviderChange align="start"/></Field><Field label="Режим разрешений"><PermissionModePicker providerId={agent.selection.providerId} value={agent.permission} onChange={permission=>update({...agent,permission})} routing={routing} align="start"/></Field><TextField label="Одновременных задач" type="number" value={String(agent.concurrency)} onChange={v=>update({...agent,concurrency:Math.max(1,Math.min(8,Number(v)||1))})}/></div></Panel><Panel title="Рабочая папка"><p className="text-sm">Наследуется от проекта задачи. При передаче между отделами проект и рабочая машина сохраняются.</p><p className="mt-2 text-xs text-muted-foreground">Проверка совместимости и изоляции этого CLI ещё не выполнена.</p></Panel></>}
 {tab==="Возможности"&&<><PageHead level={2} title="Разрешённые навыки" description={`Выбрано: ${agent.skills.length}. Демонстрационный каталог; реальная фильтрация ещё не подключена.`}><Button variant="outline" onClick={()=>update({...agent,skills:[]})}>Снять все</Button></PageHead><SearchInput aria-label="Поиск навыков" placeholder="Найти навык…" value={q} onChange={e=>setQ(e.target.value)}/><Checks options={skillOptions.filter(s=>s.includes(q.toLowerCase()))} selected={agent.skills} onChange={skills=>update({...agent,skills})}/></>}
 {tab==="Возможности"&&<><PageHead level={2} title="Подключения MCP" description="Выбор в макете не выдаёт и не отзывает реальные доступы."/><Checks options={mcpOptions} selected={agent.mcps} onChange={mcps=>update({...agent,mcps})}/><CustomMcpEditor items={agent.customMcps||[]} reservedNames={mcpOptions} onChange={customMcps=>update({...agent,customMcps})}/><Panel title="Дополнительные возможности"><div className="flex items-center justify-between py-3"><span className="text-sm">Команды терминала</span><Switch aria-label="Команды терминала" checked={shell} onCheckedChange={setShell}/></div><div className="flex items-center justify-between py-3"><span className="text-sm">Передача работы другим сотрудникам</span><Switch aria-label="Делегирование" checked={delegate} onCheckedChange={setDelegate}/></div><p className="text-xs text-muted-foreground">Доступ к файлам, сети и административным командам проверяется отдельно от видимости MCP.</p></Panel></>}
 {tab==="Исполнение"&&<><Panel title="Что получит сотрудник"><Rows rows={[["Навыки",agent.skills.join(", ")||"Не выбраны"],["MCP",[...agent.mcps,...(agent.customMcps||[]).filter(m=>m.enabled).map(m=>m.name)].join(", ")||"Не выбраны"],["CLI",agent.selection.providerId],["Модель",agent.selection.model||"Выбирается в каталоге BB"],["Изоляция","Не проверена — реальный запуск закрыт"]]}/><Button variant="outline" onClick={()=>notice("Предпросмотр обновлён. Проверка реального процесса будет доступна после этапа изоляции.")}>Проверить конфигурацию</Button></Panel><Empty title="Тестовое поручение пока недоступно" description="Здесь появится пробный запуск с просмотром фактически переданных навыков и инструментов."/></>}
 {tab==="История"&&<Panel title="Версии профиля"><Rows rows={[["Черновик","Изменения текущего прототипа"],["Версия 1","Пример исходного профиля"],["Исполнения","Будут привязаны к неизменяемой версии"]]}/></Panel>}
 </div></div>;
}
export function GroupsPage({ groups, kind, open, create }: {groups:Group[];kind:"projects"|"departments";open:(id:string)=>void;create:()=>void}) {
 const [q,setQ]=useState("");const isProject=kind==="projects";const filtered=groups.filter(g=>(g.name+g.description).toLowerCase().includes(q.toLowerCase()));
 return <div className="space-y-4"><PageHead title={isProject?"Проекты":"Отделы"} description={isProject?"Цели, материалы и команды, которые над ними работают.":"Направления работы, руководители и состав."}><Button onClick={create}>{isProject?"Создать проект":"Создать отдел"}</Button></PageHead><div className="flex items-center gap-3"><SearchInput className="max-w-xs" aria-label={isProject?"Поиск проектов":"Поиск отделов"} placeholder="Поиск по названию…" value={q} onChange={e=>setQ(e.target.value)}/><span className="ml-auto text-xs text-muted-foreground">Всего: {filtered.length}</span></div><Collection columns={[isProject?"Проект":"Отдел","Состояние","Руководитель","Состав"]} rows={filtered.map(g=>({id:g.id,open:()=>open(g.id),name:<span className="flex items-center gap-3"><span className="rounded-md bg-muted p-2"><Icon name={isProject?"Folder":"Workflow"} className="size-4"/></span><span><span className="block font-medium">{g.name}</span><span className="mt-0.5 block max-w-sm text-xs text-muted-foreground">{g.description}</span></span></span>,cells:[g.enabled?"Активен":"На паузе",g.lead,`${isProject?"Отделы":"Сотрудники"}: ${g.members.length}`]}))}/></div>;
}
export function GroupDetail({ group, kind, update, jobs, setJobs, openJob, back, notice, people, agents, departments, openAgent, openDepartment }: {group:Group;kind:"projects"|"departments";update:(g:Group)=>void;jobs:Job[];setJobs:(j:Job[])=>void;openJob:(id:string)=>void;back:()=>void;notice:(s:string)=>void;people:string[];agents:Agent[];departments:Group[];openAgent:(id:string)=>void;openDepartment:(id:string)=>void}) {
 const [tab,setTab]=useState("Обзор");const returnLimit=group.returnLimit||"2";const setReturnLimit=(returnLimit:string)=>update({...group,returnLimit});const [teamView,setTeamView]=useState("Схема");const isProject=kind==="projects";const relatedJobs=jobs.filter(j=>isProject?j.project===group.name:j.department===group.name);
 return <div className="space-y-5"><Button variant="ghost" size="sm" onClick={back}>← {isProject?"Проекты":"Отделы"}</Button><PageHead title={group.name} description={group.description}><Button variant="outline" onClick={()=>update({...group,enabled:!group.enabled})}>{group.enabled?"Пауза":"Продолжить"}</Button><Button onClick={()=>notice("Настройки сохранены в текущем прототипе.")}>Сохранить</Button></PageHead><TabBar value={tab} onChange={setTab} tabs={["Обзор","Задачи",isProject?"Отделы":"Сотрудники","Настройки",...(isProject?["Менеджер"]:[])]}/>
 {tab==="Обзор"&&<div className="space-y-6"><section className="rounded-xl border border-border bg-muted/30 p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs text-muted-foreground">{isProject?"Цель проекта":"Задача отдела"}</p><h2 className="mt-2 text-base font-semibold">{group.description}</h2><p className="mt-2 text-sm text-muted-foreground">{isProject?"Менеджер":"Руководитель"}: {group.lead} · {group.enabled?"Работа разрешена в примере":"На паузе"}</p></div><Button size="sm" onClick={()=>setTab("Задачи")}>Открыть задачи</Button></div></section><div className="flex flex-wrap gap-4 text-sm"><span>В работе: {relatedJobs.filter(j=>j.state==="running").length}</span><span>Ждут решения или проверки: {relatedJobs.filter(j=>j.state==="blocked"||j.state==="review").length}</span><span>Всего задач: {relatedJobs.length}</span></div><div className="grid gap-6 md:grid-cols-2"><Panel title={isProject?"Подключённые отделы":"Состав команды"}><Rows rows={group.members.map(name=>[name,"Подключён"] as [string,string])}/>{!group.members.length&&<p className="text-sm text-muted-foreground">Состав ещё не выбран.</p>}<Button size="sm" variant="ghost" onClick={()=>setTab(isProject?"Отделы":"Сотрудники")}>Настроить состав</Button></Panel><Panel title="Порядок работы"><p className="text-sm leading-relaxed">{group.instructions||"Порядок работы ещё не задан."}</p><Button size="sm" variant="ghost" className="mt-3" onClick={()=>setTab("Настройки")}>Изменить правила</Button></Panel></div></div>}
 {tab==="Настройки"&&<Panel title="Основное"><div className="grid gap-4 md:grid-cols-2"><TextField label="Название" value={group.name} onChange={name=>update({...group,name})}/><TextField label="Назначение" value={group.description} onChange={description=>update({...group,description})}/></div></Panel>}

 {tab==="Задачи"&&<JobsPage jobs={jobs} setJobs={setJobs} open={openJob} {...(isProject?{project:group.name}:{department:group.name})}/>}
 {(tab==="Сотрудники"||tab==="Отделы")&&<div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-sm font-semibold">Структура команды</h2><div className="flex gap-1 rounded-lg border border-border p-1" role="group" aria-label="Вид команды">{["Схема","Список","Состав"].map(view=><Button key={view} size="sm" variant={teamView===view?"secondary":"ghost"} aria-pressed={teamView===view} onClick={()=>setTeamView(view)}>{view}</Button>)}</div></div>
 {teamView==="Схема"&&<OrgChart group={group} kind={kind} agents={agents} departments={departments} openAgent={openAgent} openDepartment={openDepartment}/>}
 {teamView==="Список"&&<div className="space-y-4"><Rows rows={[[isProject?"Менеджер проекта":"Руководитель отдела",group.lead]]}/><Collection columns={[isProject?"Отдел":"Сотрудник",isProject?"Руководитель":"Роль"]} rows={group.members.map(name=>{const a=agents.find(a=>a.name===name);const d=departments.find(d=>d.name===name);return {id:name,name,cells:[isProject?d?.lead||"Не назначен":name===group.lead?"Руководитель":a?.role||"Сотрудник"],open:()=>{if(isProject&&d)openDepartment(d.id);else if(a)openAgent(a.id);}};})}/></div>}
 {teamView==="Состав"&&<div className="max-w-3xl space-y-4"><Field label={isProject?"Менеджер проекта":"Руководитель отдела"}><Choice label="Руководитель" value={group.lead} onChange={lead=>update({...group,lead})} options={agents.map(a=>a.name)}/></Field><Field label={isProject?"Подключённые отделы":"Сотрудники отдела"} hint="Схема обновляется при изменении состава. В прототипе изменения хранятся до обновления страницы."><Checks options={people} selected={group.members} onChange={members=>update({...group,members})}/></Field></div>}</div>}
 {tab==="Настройки"&&<div className="max-w-3xl space-y-4"><TextField label={isProject?"Правила проекта":"Как работает отдел"} multiline value={group.instructions} onChange={instructions=>update({...group,instructions})}/><p className="text-xs text-muted-foreground">{isProject?"Общие требования для всех задач: аудитория, стиль, материалы и ограничения.":"Опишите шаги и ответственных. Например: автор готовит текст → редактор проверяет → автор исправляет замечания."}</p><TextField label="Критерии приёмки результата" multiline value={group.acceptance||""} onChange={acceptance=>update({...group,acceptance})}/><p className="text-xs text-muted-foreground">Что нужно проверить перед принятием: например, файл приложен, факты подтверждены, замечания учтены. Задача может добавить свои требования.</p><TextField label="Максимум возвратов на доработку" type="number" value={returnLimit} onChange={setReturnLimit}/><Panel title="Передача между отделами"><p className="text-sm">Заявка сохраняет проект, входные материалы, срок и ответственного за общий результат. Готовность дочерней задачи уведомляет руководителя.</p></Panel></div>}
 {tab==="Настройки"&&<Panel title={isProject?"Канон проекта":"Материалы отдела"}><Rows rows={[["Правила","AGENTS.md · пример привязки"],["Материалы","Позиционирование и критерии приёмки"],["Источник","Рабочая папка проекта задачи"],["Память","Только подтверждённые факты с источниками"]]}/><Button variant="outline" onClick={()=>notice("В полном продукте здесь выбирается источник через файловые средства BB. Макет не меняет привязки проекта.")}>Подключить материалы</Button></Panel>}
 {tab==="Менеджер"&&<Panel title="Поручение менеджеру проекта"><p className="mb-4 text-sm text-muted-foreground">Предпросмотр штатного редактора BB. Отправка здесь показывает подтверждение макета и не создаёт чат.</p><NewThreadComposer layout="document" draftKey={`agency-prototype-${group.id}`} placeholder="Какой результат нужен проекту?" onSubmit={async()=>{notice("Поручение показано в прототипе. Реальный чат и работники не созданы.");}}/></Panel>}
 {tab==="Настройки"&&<Panel title="Когда включается руководитель"><Rows rows={[["Новое поручение","Определяет состав и следующий шаг"],["Результат принят","Продолжает зависимые этапы"],["Нужен выбор","Обращается к владельцу"],["Режим прототипа","События не запускают агентов"]]}/><Button variant="outline" onClick={()=>notice("Пробное событие показало бы маршрут: руководитель → исполнитель → проверяющий. Событие не отправлено.")}>Предпросмотр маршрута</Button></Panel>}
 </div>;
}
