import { SearchInput } from "./shared";
import { useEffect, useState } from "react";
import { experimental_NewThreadComposer as NewThreadComposer } from "@get-bb/plugin-sdk/app";
import { agentLabel, departmentLabel, resolveAgent, resolveDepartment, usesCatalogIds } from "../data/group-refs";
import { linksForProject } from "../data/job-placement";
import { type Agent, type Group, type Job } from "./data";
import { Button, AgentMark, TextField, Field, Choice, PageHead, TabBar, Panel, Checks, Rows, Collection, Icon } from "./shared";
import { JobsPage } from "./jobs";
import { OrgChart } from "./org-chart";

export function AgentsPage({ agents, open, create }: {agents:Agent[];open:(id:string)=>void;create:()=>void}) {
 const [q,setQ]=useState("");const [dep,setDep]=useState("all");
 const filtered=agents.filter(a=>(a.name+" "+a.role).toLowerCase().includes(q.toLowerCase())&&(dep==="all"||a.department===dep));
 return <div className="space-y-4"><PageHead title="Сотрудники" description="Кто выполняет работу и какие возможности ему доступны."><Button onClick={create}>Создать сотрудника</Button></PageHead><div className="flex flex-wrap items-center gap-2"><SearchInput className="max-w-xs" aria-label="Поиск сотрудников" placeholder="Найти по имени или роли…" value={q} onChange={e=>setQ(e.target.value)}/><div className="w-44"><Choice label="Отдел сотрудника" value={dep} onChange={setDep} options={[{value:"all",label:"Все отделы"},...new Set(agents.map(a=>a.department))]}/></div><span className="ml-auto text-xs text-muted-foreground">{filtered.length} сотрудников</span></div><Collection columns={["Сотрудник","Состояние","Отдел","Возможности","CLI"]} rows={filtered.map(a=>({id:a.id,open:()=>open(a.id),name:<span className="flex items-center gap-3"><span className="flex size-8 shrink-0 items-center justify-center rounded-full border border-border bg-muted"><AgentMark id={a.selection.providerId} className="size-5"/></span><span><span className="block font-medium">{a.name}</span><span className="block text-xs text-muted-foreground">{a.role}</span></span></span>,cells:[a.enabled?"Профиль включён":"На паузе",a.department,`Навыки: ${a.skills.length} · MCP: ${a.mcps.length+(a.customMcps?.filter(m=>m.enabled).length||0)}`,a.selection.providerId]}))}/></div>;

}
export { AgentDetail } from "./agent-detail";
export function GroupsPage({ groups, kind, open, create, agents = [] }: {groups:Group[];kind:"projects"|"departments";open:(id:string)=>void;create:()=>void;agents?:Agent[]}) {
 const [q,setQ]=useState("");const isProject=kind==="projects";const filtered=groups.filter(g=>(g.name+g.description).toLowerCase().includes(q.toLowerCase()));
 return <div className="space-y-4"><PageHead title={isProject?"Проекты":"Отделы"} description={isProject?"Цели, материалы и команды, которые над ними работают.":"Направления работы, руководители и состав."}><Button onClick={create}>{isProject?"Привязать проект":"Создать отдел"}</Button></PageHead><div className="flex items-center gap-3"><SearchInput className="max-w-xs" aria-label={isProject?"Поиск проектов":"Поиск отделов"} placeholder="Поиск по названию…" value={q} onChange={e=>setQ(e.target.value)}/><span className="ml-auto text-xs text-muted-foreground">Всего: {filtered.length}</span></div><Collection columns={[isProject?"Проект":"Отдел","Состояние","Руководитель","Состав"]} rows={filtered.map(g=>({id:g.id,open:()=>open(g.id),name:<span className="flex items-center gap-3"><span className="rounded-md bg-muted p-2"><Icon name={isProject?"Folder":"Workflow"} className="size-4"/></span><span><span className="block font-medium" title={g.description}>{g.name}</span><span className="mt-0.5 block max-w-sm truncate text-xs text-muted-foreground" title={g.description}>{g.description}</span></span></span>,cells:[g.enabled?"Активен":"На паузе",isProject?(g.lead||"—"):agentLabel(agents,g.lead),`${isProject?"Отделы":"Сотрудники"}: ${g.members.length}`]}))}/></div>;
}
export function GroupDetail({ group, kind, update, jobs, setJobs, openJob, back, notice, people, agents, departments, projects = [], openAgent, openDepartment, persist, commit, live = false }: {group:Group;kind:"projects"|"departments";update:(g:Group)=>void;jobs:Job[];setJobs:(j:Job[])=>void;openJob:(id:string)=>void;back:()=>void;notice:(s:string)=>void;people:string[];agents:Agent[];departments:Group[];projects?:Group[];openAgent:(id:string)=>void;openDepartment:(id:string)=>void;persist?:(job:Job)=>void|Promise<boolean>;commit?:(g:Group)=>void|Promise<boolean>;live?:boolean}) {
 const [tab,setTab]=useState("Обзор");const returnLimit=group.returnLimit||"2";const setReturnLimit=(returnLimit:string)=>update({...group,returnLimit});const [teamView,setTeamView]=useState("Схема");const isProject=kind==="projects";const catalogIds=usesCatalogIds(group,agents,departments);const leadName=agentLabel(agents,group.lead);const memberLabel=(ref:string)=>isProject?departmentLabel(departments,ref):agentLabel(agents,ref);const relatedJobs=jobs.filter(j=>isProject?j.bindingId===group.id||j.project===group.id:j.departmentId===group.id||j.department===group.id);const projectFieldsLocked=live&&isProject;const [linkedDepartments,setLinkedDepartments]=useState(group.members);
 useEffect(()=>{setLinkedDepartments(group.members);},[group.id,group.revision,group.recordId]);
 return <div className="space-y-5"><Button variant="ghost" size="sm" onClick={back}>← {isProject?"Проекты":"Отделы"}</Button><PageHead title={group.name} description={group.description}><Button variant="outline" disabled={live} onClick={()=>update({...group,enabled:!group.enabled})}>{group.enabled?"Пауза":"Продолжить"}</Button><Button onClick={()=>{if(commit)void commit(group);else if(!live)notice("Настройки сохранены в текущем прототипе.");}}>Сохранить</Button></PageHead>{live&&isProject&&<p className="text-xs text-muted-foreground">Сохраняется только список отделов на этой папке. Руководитель, назначение, пауза, лимит возвратов и материалы в привязке не пишутся.</p>}<TabBar value={tab} onChange={setTab} tabs={["Обзор","Задачи",isProject?"Отделы":"Сотрудники","Настройки",...(isProject?["Менеджер"]:[])]}/>
 {tab==="Обзор"&&<div className="space-y-6"><section className="rounded-xl border border-border bg-muted/30 p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs text-muted-foreground">{isProject?"Цель проекта":"Задача отдела"}</p><h2 className="mt-2 text-base font-semibold">{group.description}</h2><p className="mt-2 text-sm text-muted-foreground">{isProject?"Менеджер":"Руководитель"}: {leadName} · {group.enabled?"Работа разрешена в примере":"На паузе"}</p></div><Button size="sm" onClick={()=>setTab("Задачи")}>Открыть задачи</Button></div></section><div className="flex flex-wrap gap-4 text-sm"><span>В работе: {relatedJobs.filter(j=>j.state==="running").length}</span><span>Ждут решения или проверки: {relatedJobs.filter(j=>j.state==="blocked"||j.state==="review").length}</span><span>Всего задач: {relatedJobs.length}</span></div><div className="grid gap-6 md:grid-cols-2"><Panel title={isProject?"Подключённые отделы":"Состав команды"}><Rows rows={group.members.map(ref=>[memberLabel(ref),"Подключён"] as [string,string])}/>{!group.members.length&&<p className="text-sm text-muted-foreground">Состав ещё не выбран.</p>}<Button size="sm" variant="ghost" onClick={()=>setTab(isProject?"Отделы":"Сотрудники")}>Настроить состав</Button></Panel><Panel title="Порядок работы"><p className="text-sm leading-relaxed">{group.instructions||"Порядок работы ещё не задан."}</p><Button size="sm" variant="ghost" className="mt-3" onClick={()=>setTab("Настройки")}>Изменить правила</Button></Panel></div></div>}
 {tab==="Настройки"&&<Panel title="Основное"><div className="grid gap-4 md:grid-cols-2"><TextField label="Название" value={group.name} disabled={projectFieldsLocked} hint={projectFieldsLocked?"Название берётся из папки и машины, в привязке отдельно не хранится.":undefined} onChange={name=>update({...group,name})}/><TextField label="Назначение" value={group.description} disabled={projectFieldsLocked} hint={projectFieldsLocked?"Это путь папки проекта, не редактируемое поле карточки.":undefined} onChange={description=>update({...group,description})}/></div></Panel>}

 {tab==="Задачи"&&<JobsPage jobs={jobs} setJobs={setJobs} open={openJob} notice={notice} {...(isProject?{project:group.id}:{department:group.id})} persist={persist} requirePlacement placements={isProject?{projects:[{id:group.id,name:group.name}],departments:departments.map(item=>({id:item.id,name:item.name})),projectDepartments:linksForProject(group.id,group.members,departments)}:{projects:projects.filter(item=>item.members.some(ref=>ref===group.id||ref===group.name)).map(item=>({id:item.id,name:item.name})),departments:[{id:group.id,name:group.name}],projectDepartments:projects.filter(item=>item.members.some(ref=>ref===group.id||ref===group.name)).map(item=>({bindingId:item.id,departmentId:group.id}))}}/>}
 {(tab==="Сотрудники"||tab==="Отделы")&&<div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-sm font-semibold">Структура команды</h2><div className="flex gap-1 rounded-lg border border-border p-1" role="group" aria-label="Вид команды">{["Схема","Список","Состав"].map(view=><Button key={view} size="sm" variant={teamView===view?"secondary":"ghost"} aria-pressed={teamView===view} onClick={()=>setTeamView(view)}>{view}</Button>)}</div></div>
 {teamView==="Схема"&&<OrgChart group={group} kind={kind} agents={agents} departments={departments} openAgent={openAgent} openDepartment={openDepartment}/>}
 {teamView==="Список"&&<div className="space-y-4"><Rows rows={[[isProject?"Менеджер проекта":"Руководитель отдела",leadName]]}/><Collection columns={[isProject?"Отдел":"Сотрудник",isProject?"Руководитель":"Роль"]} rows={group.members.map(ref=>{const a=resolveAgent(agents,ref);const d=resolveDepartment(departments,ref);return {id:ref,name:memberLabel(ref),cells:[isProject?agentLabel(agents,d?.lead||""):ref===group.lead?"Руководитель":a?.role||"Сотрудник"],open:()=>{if(isProject&&d)openDepartment(d.id);else if(a)openAgent(a.id);}};})}/></div>}
 {teamView==="Состав"&&<div className="max-w-3xl space-y-4"><Field label={isProject?"Менеджер проекта":"Руководитель отдела"} hint={projectFieldsLocked?"Руководитель проекта в привязке папки не хранится.":undefined}><Choice label="Руководитель" value={group.lead} disabled={projectFieldsLocked} onChange={lead=>update({...group,lead})} options={catalogIds?agents.map(a=>({value:a.id,label:a.name})):agents.map(a=>a.name)}/></Field><Field label={isProject?"Подключённые отделы":"Сотрудники отдела"} hint={live&&isProject?"Отметьте отдел и нажмите «Сохранить». Уже подключённый отдел снять нельзя — такого RPC нет.":live?"Состав пишется в отдел по идентификаторам сотрудников.":"Схема обновляется при изменении состава. В прототипе изменения хранятся до обновления страницы."}><Checks options={catalogIds?(isProject?departments.map(d=>({value:d.id,label:d.name})):agents.map(a=>({value:a.id,label:a.name}))):people} selected={group.members} locked={live&&isProject?linkedDepartments:[]} onChange={members=>update({...group,members})}/></Field></div>}</div>}
 {tab==="Настройки"&&<div className="max-w-3xl space-y-4"><TextField label={isProject?"Правила проекта":"Как работает отдел"} multiline value={group.instructions} disabled={projectFieldsLocked} onChange={instructions=>update({...group,instructions})}/><p className="text-xs text-muted-foreground">{projectFieldsLocked?"Правила проекта в привязке папки не хранятся.":isProject?"Общие требования для всех задач: аудитория, стиль, материалы и ограничения.":"Опишите шаги и ответственных. Например: автор готовит текст → редактор проверяет → автор исправляет замечания."}</p><TextField label="Критерии приёмки результата" multiline value={group.acceptance||""} disabled={projectFieldsLocked} onChange={acceptance=>update({...group,acceptance})}/><p className="text-xs text-muted-foreground">{projectFieldsLocked?"Критерии приёмки задаются в отделе и в задаче.":"Что нужно проверить перед принятием: например, файл приложен, факты подтверждены, замечания учтены. Задача может добавить свои требования."}</p><TextField label="Максимум возвратов на доработку" type="number" value={returnLimit} disabled={live} hint={live?"Лимит возвратов в каталоге не хранится.":undefined} onChange={setReturnLimit}/><Panel title="Передача между отделами"><p className="text-sm">Заявка сохраняет проект, входные материалы, срок и ответственного за общий результат. Готовность дочерней задачи уведомляет руководителя.</p></Panel></div>}
 {tab==="Настройки"&&<Panel title={isProject?"Канон проекта":"Материалы отдела"}><Rows rows={[["Правила","AGENTS.md · пример привязки"],["Материалы","Позиционирование и критерии приёмки"],["Источник","Рабочая папка проекта задачи"],["Память","Только подтверждённые факты с источниками"]]}/><Button variant="outline" disabled={live} onClick={()=>{if(!live)notice("В полном продукте здесь выбирается источник через файловые средства BB. Макет не меняет привязки проекта.");}}>{live?"Материалы задаёт папка проекта":"Подключить материалы"}</Button></Panel>}
 {tab==="Менеджер"&&<Panel title="Поручение менеджеру проекта">{live?<p className="text-sm text-muted-foreground">Из карточки проекта чат менеджеру не создаётся. Поручение пишите задачей в этой папке.</p>:<><p className="mb-4 text-sm text-muted-foreground">Предпросмотр штатного редактора BB. Отправка здесь показывает подтверждение макета и не создаёт чат.</p><NewThreadComposer layout="document" draftKey={`agency-prototype-${group.id}`} placeholder="Какой результат нужен проекту?" onSubmit={async()=>{notice("Поручение показано в прототипе. Реальный чат и работники не созданы.");}}/></>}</Panel>}
 {tab==="Настройки"&&<Panel title="Когда включается руководитель"><Rows rows={[["Новое поручение","Определяет состав и следующий шаг"],["Результат принят","Продолжает зависимые этапы"],["Нужен выбор","Обращается к владельцу"],["Режим прототипа","События не запускают агентов"]]}/><Button variant="outline" disabled={live} onClick={()=>{if(!live)notice("Пробное событие показало бы маршрут: руководитель → исполнитель → проверяющий. Событие не отправлено.");}}>Предпросмотр маршрута</Button></Panel>}
 </div>;
}
