import { useState } from 'react';
import { Markdown } from '@get-bb/plugin-sdk/app';
import { AgentMark, Button, Collection, PageHead, Panel, Rows } from './shared';
import './job-detail.css';
export function RunsPage({detail,open,back,openJob,go}:{detail:boolean;open:()=>void;back:()=>void;notice:(s:string)=>void;openJob:()=>void;go?:(section:string,id?:string)=>void}) {
 const [expanded,setExpanded]=useState(false);
 if(!detail)return <div className="space-y-4"><PageHead title="Запуски" description="Попытки выполнения задач: кто работал и чем закончилась работа."/><Collection columns={['Запуск','Результат','Задача','Проект / отдел']} rows={[{id:'RUN-204',open,name:<span className="flex items-center gap-3"><AgentMark id="codex"/><span><span className="block font-medium">Подготовка оффера</span><span className="text-xs text-muted-foreground">RUN-204 · Анна</span></span></span>,cells:['Передан на проверку','AG-102','SelfyStudio · Редакция']}]}/></div>;
 return <article className="agency-task-layout mx-auto w-full max-w-7xl px-1 pb-8 sm:px-4"><nav className="mb-4 flex items-center gap-2 text-xs text-muted-foreground" aria-label="Путь запуска"><Button variant="ghost" size="sm" onClick={back}>← Запуски</Button><span>/ RUN-204</span></nav><div className="agency-task-grid">
 <header className="agency-task-title"><PageHead title="Подготовка оффера" description="Анна подготовила результат и передала его на проверку."><Button variant="outline" onClick={openJob}>К задаче AG-102</Button></PageHead><p className="text-xs text-muted-foreground">RUN-204 · Пример завершённой попытки · 3 мин 42 с</p></header>
 <main className="agency-task-content space-y-5"><section className="rounded-lg border border-border bg-muted/25 p-4"><h2 className="mb-2 text-sm font-semibold">Результат работы</h2><Markdown content={'Подготовлен **оффер v2**. Уточнена аудитория, удалены неподтверждённые обещания.\n\nОстаётся согласовать визуальную концепцию.'}/><Button size="sm" variant="outline" className="mt-3" onClick={openJob}>Посмотреть файлы и принять результат</Button></section>
 <Panel title="Как проходила работа"><ol className="ml-3 border-l border-border">{[
 ['10:14','Начала работу','Анна получила бриф v1 и материалы исследования.'],
 ['10:16','Подготовила оффер','Текст уточнён по аудитории и условиям услуги.'],
 ['10:18','Передала результат на проверку','Создана версия 2 файла «Оффер.md». Решение по задаче ещё не принято.'],
 ].map(([time,title,text])=><li key={time} className="relative pb-5 pl-6 last:pb-0"><span className="absolute -left-3 flex size-6 items-center justify-center rounded-full border border-border bg-background"><AgentMark id="codex" className="size-4"/></span><div className="flex flex-wrap items-baseline gap-2 text-sm"><strong className="font-medium">{title}</strong><time className="text-xs text-muted-foreground">{time}</time></div><p className="mt-1 text-sm text-muted-foreground">{text}</p></li>)}</ol></Panel>
 <details className="border-b border-border pb-3"><summary className="cursor-pointer text-sm font-medium">Технические подробности</summary><div className="mt-3"><Rows rows={[["Тип записи","Демонстрация"],["Реальный чат BB","Не создан"],["Модель и расход","Не измерялись"],["Повтор или передача","Назначаются из задачи отдельной новой попыткой"]]}/></div></details></main>
 <aside className="agency-task-sidebar rounded-lg border border-border bg-muted/20 p-4" data-expanded={expanded}><h2 className="agency-task-sidebar-heading text-sm font-semibold">Сведения о запуске</h2><Button variant="ghost" className="agency-task-sidebar-toggle w-full justify-between" onClick={()=>setExpanded(!expanded)}>Сведения о запуске <span>{expanded?'−':'+'}</span></Button><div className="agency-task-sidebar-content"><Rows rows={[["Задача",<button className="underline underline-offset-4" onClick={openJob}>AG-102 · Оффер новой услуги</button>],["Проект","SelfyStudio"],["Отдел","Редакция"],["Сотрудник",<span className="inline-flex items-center gap-2"><AgentMark id="codex" className="size-4"/>Анна</span>],["Профиль","Версия 1"],["Навыки","copywriter, ru-text"],["MCP","Документы"],["Входные материалы","Бриф v1"],["Выходные материалы","Оффер v2"]]}/><p className="mt-3 text-xs text-muted-foreground">Сведения фиксируются на начало попытки. Переназначение задачи не меняет историю этого запуска.</p><Button className="mt-3 w-full" variant="outline" size="sm" onClick={openJob}>Передать работу из задачи</Button></div></aside>
 </div></article>;
}
