import { useId, type ReactNode } from "react";
import { Button } from "../../../components/ui/button";
import { Input } from "../../../components/ui/input";
import { Textarea } from "../../../components/ui/textarea";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "../../../components/ui/select";
import { Tabs, TabsList, TabsTrigger } from "../../../components/ui/tabs";
import { Checkbox } from "../../../components/ui/checkbox";
import { Icon } from "../../../components/ui/icon";
import { stateNames, type State } from "./data";
export { Button, Input, Textarea, Checkbox, Icon };
export function Field({ label, hint, children }: { label: string; hint?: string; children: ReactNode }) { return <div className="space-y-1.5"><div className="text-sm font-medium">{label}</div>{children}{hint && <p className="text-xs text-muted-foreground">{hint}</p>}</div>; }
export function TextField({ label, value, onChange, multiline = false, type = "text" }: { label: string; value: string; onChange: (v: string) => void; multiline?: boolean; type?: string }) { const id = useId(); return <div className="space-y-1.5"><label htmlFor={id} className="text-sm font-medium">{label}</label>{multiline ? <Textarea id={id} value={value} onChange={e => onChange(e.target.value)} rows={6}/> : <Input id={id} type={type} value={value} onChange={e => onChange(e.target.value)}/>}</div>; }
export function Choice({ label, value, onChange, options }: { label: string; value: string; onChange: (v: string) => void; options: readonly (string | { value: string; label: string })[] }) { return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="w-full min-w-0"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o => <SelectItem key={typeof o === "string" ? o : o.value} value={typeof o === "string" ? o : o.value}>{typeof o === "string" ? o : o.label}</SelectItem>)}</SelectContent></Select>; }
export function PageHead({ title, description, children }: { title: string; description?: string; children?: ReactNode }) { return <header className="flex flex-wrap items-center justify-between gap-3 border-b border-border pb-3"><div><h1 className="text-sm font-semibold tracking-tight">{title}</h1>{description && <p className="mt-1 text-sm text-muted-foreground">{description}</p>}</div><div className="flex flex-wrap items-center gap-2">{children}</div></header>; }
export function TabBar({ value, onChange, tabs }: { value: string; onChange: (v: string) => void; tabs: readonly string[] }) { return <Tabs value={value} onValueChange={onChange}><div className="overflow-x-auto"><TabsList className="w-max justify-start">{tabs.map(t => <TabsTrigger value={t} key={t}>{t}</TabsTrigger>)}</TabsList></div></Tabs>; }
export function Panel({ title, children }: { title?: string; children: ReactNode }) { return <section className="border-b border-border py-3">{title && <h2 className="mb-3 text-sm font-semibold">{title}</h2>}{children}</section>; }
export function Status({ state }: { state: State }) { const icon = state === "done" ? "CircleCheck" : state === "review" ? "Eye" : state === "blocked" ? "AlertCircle" : state === "running" ? "Play" : "Circle"; return <span className="inline-flex items-center gap-1.5 whitespace-nowrap text-xs"><Icon name={icon} className={`size-3.5 ${state === "running" ? "text-amber-500" : state === "review" ? "text-blue-500" : state === "done" ? "text-emerald-500" : state === "blocked" ? "text-orange-500" : "text-muted-foreground"}`}/>{stateNames[state]}</span>; }
export function Checks({ options, selected, onChange }: { options: readonly string[]; selected: string[]; onChange: (v: string[]) => void }) { return <div className="divide-y divide-border rounded-lg border border-border">{options.map(v => <label key={v} className="flex cursor-pointer items-center gap-2 px-3 py-2 text-sm hover:bg-muted/50"><Checkbox checked={selected.includes(v)} onCheckedChange={checked => onChange(checked ? [...selected, v] : selected.filter(x => x !== v))}/><span>{v}</span></label>)}</div>; }
export function Empty({ title, description }: { title: string; description: string }) { return <div className="rounded-lg border border-dashed border-border px-5 py-10 text-center"><p className="font-medium">{title}</p><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>; }
export function Rows({ rows }: { rows: [string, ReactNode][] }) { return <dl className="divide-y divide-border">{rows.map(([k,v]) => <div key={k} className="flex flex-wrap justify-between gap-3 py-2 text-sm"><dt className="text-muted-foreground">{k}</dt><dd className="max-w-full break-words">{v}</dd></div>)}</dl>; }
