import { experimental_ProviderIcon, experimental_useProviders } from "@get-bb/plugin-sdk/app";
import { useId, type ComponentProps, type ReactNode } from "react";
import { Button } from "../../../components/ui/button";
import { Input } from "../../../components/ui/input";
import { Textarea } from "../../../components/ui/textarea";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "../../../components/ui/select";
import { Tabs, TabsList, TabsTrigger } from "../../../components/ui/tabs";
import { Checkbox } from "../../../components/ui/checkbox";
import { Icon } from "../../../components/ui/icon";
import { stateNames, type State } from "./data";
export { Button, Input, Textarea, Checkbox, Icon };
export function Field({ label, hint, children }: { label: string; hint?: string; children: ReactNode }) { return <div className="space-y-1.5"><div className="text-sm font-medium">{label}</div>{children}{hint && <p className="text-xs text-muted-foreground">{hint}</p>}</div>; }
export function TextField({ label, value, onChange, multiline = false, type = "text" }: { label: string; value: string; onChange: (v: string) => void; multiline?: boolean; type?: string }) { const id = useId(); return <div className="space-y-1.5"><label htmlFor={id} className="text-sm font-medium">{label}</label>{multiline ? <Textarea id={id} value={value} onChange={e => onChange(e.target.value)} rows={6}/> : <Input id={id} type={type} value={value} onChange={e => onChange(e.target.value)}/>}</div>; }
export function Choice({ label, value, onChange, options }: { label: string; value: string; onChange: (v: string) => void; options: readonly (string | { value: string; label: string })[] }) { return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="w-full min-w-0"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o => <SelectItem key={typeof o === "string" ? o : o.value} value={typeof o === "string" ? o : o.value}>{typeof o === "string" ? o : o.label}</SelectItem>)}</SelectContent></Select>; }
export function PageHead({ title, description, children, level=1 }: { level?:1|2; title: string; description?: string; children?: ReactNode }) { const Heading=level===1?"h1":"h2"; return <header className="flex flex-wrap items-center justify-between gap-3 pb-2 [&_button]:h-8 [&_button]:text-xs"><div><Heading className={level===1?"text-lg font-semibold tracking-tight":"text-sm font-semibold"}>{title}</Heading>{description && <p className="mt-1 text-sm text-muted-foreground">{description}</p>}</div><div className="flex flex-wrap items-center gap-2">{children}</div></header>; }
export function TabBar({ value, onChange, tabs }: { value: string; onChange: (v: string) => void; tabs: readonly string[] }) { return <Tabs value={value} onValueChange={onChange}><div className="overflow-x-auto"><TabsList className="h-auto w-max justify-start gap-4 rounded-none border-b border-border bg-transparent p-0">{tabs.map(t => <TabsTrigger className="rounded-none border-b-2 border-transparent px-1 py-2 text-xs shadow-none data-[state=active]:border-foreground data-[state=active]:bg-transparent data-[state=active]:shadow-none" value={t} key={t}>{t}</TabsTrigger>)}</TabsList></div></Tabs>; }
export function Panel({ title, children }: { title?: string; children: ReactNode }) { return <section className="border-b border-border py-3">{title && <h2 className="mb-3 text-sm font-semibold">{title}</h2>}{children}</section>; }
export function Status({ state }: { state: State }) { const icon = state === "done" ? "CircleCheck" : state === "review" ? "Eye" : state === "blocked" ? "AlertCircle" : state === "running" ? "Play" : "Circle"; return <span className="inline-flex items-center gap-1.5 whitespace-nowrap text-xs"><Icon name={icon} className={`size-3.5 ${state === "running" ? "text-amber-500" : state === "review" ? "text-blue-500" : state === "done" ? "text-emerald-500" : state === "blocked" ? "text-orange-500" : "text-muted-foreground"}`}/>{stateNames[state]}</span>; }
export function Checks({ options, selected, onChange }: { options: readonly string[]; selected: string[]; onChange: (v: string[]) => void }) { return <div className="divide-y divide-border rounded-lg border border-border">{options.map(v => <label key={v} className="flex cursor-pointer items-center gap-2 px-3 py-2 text-sm hover:bg-muted/50"><Checkbox checked={selected.includes(v)} onCheckedChange={checked => onChange(checked ? [...selected, v] : selected.filter(x => x !== v))}/><span>{v}</span></label>)}</div>; }
export function Empty({ title, description }: { title: string; description: string }) { return <div className="rounded-lg border border-dashed border-border px-5 py-10 text-center"><p className="font-medium">{title}</p><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>; }
export function Rows({ rows }: { rows: [string, ReactNode][] }) { return <dl className="divide-y divide-border">{rows.map(([k,v]) => <div key={k} className="flex flex-wrap justify-between gap-3 py-2 text-sm"><dt className="text-muted-foreground">{k}</dt><dd className="max-w-full break-words">{v}</dd></div>)}</dl>; }

export function Collection({columns,rows}:{columns:string[];rows:{id:string;name:ReactNode;cells:ReactNode[];open:()=>void}[]}) {
 return <div className="overflow-x-auto rounded-lg border border-border"><table className="w-full text-left text-sm"><thead className="bg-muted/40 text-xs text-muted-foreground"><tr>{columns.map((c,i)=><th key={c} className={`px-4 py-2 font-medium ${i>1?"hidden md:table-cell":""}`}>{c}</th>)}</tr></thead><tbody className="divide-y divide-border">{rows.map(row=><tr key={row.id} className="hover:bg-muted/30"><td className="px-4 py-3"><button className="text-left focus-visible:outline focus-visible:outline-ring" onClick={row.open}>{row.name}</button></td>{row.cells.map((c,i)=><td key={i} className={`px-4 py-3 text-xs text-muted-foreground ${i>0?"hidden md:table-cell":""}`}>{c}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="p-6 text-sm text-muted-foreground">Ничего не найдено. Измените фильтры.</p>}</div>;
}

export function AgentMark({id,className="size-5"}:{id:string;className?:string}) { const {providers}=experimental_useProviders();const ProviderIcon=experimental_ProviderIcon;return <ProviderIcon providerKind="agent" provider={providers.find(p=>p.id===id)||{id}} fallback="Bot" className={className}/>; }

export function SearchInput({className="",...props}:ComponentProps<"input">) {
 return <div className={`relative w-full max-w-sm ${className}`}><Icon name="Search" aria-hidden className="pointer-events-none absolute left-3 top-1/2 z-10 size-4 -translate-y-1/2 text-muted-foreground"/><Input {...props} type="search" className="h-9 border-foreground/25 bg-muted/30 pl-9 pr-3 shadow-sm hover:border-foreground/40 focus-visible:bg-background"/></div>;
}
