import { TelegramSettings } from "./telegram";
import { MachinesPage } from "./machines";
import { useState } from "react";
import { Switch } from "../../../components/ui/switch";
import { Button, TextField, Choice, PageHead, TabBar, Panel, Field, Rows } from "./shared";
export { RunsPage } from "./runs";
export interface AgencySettings {limit:string;paused:boolean;tz:string;days:string;}
export const seedSettings:AgencySettings={limit:"3",paused:false,tz:"Europe/Madrid",days:"30"};
export function SettingsPage({hosts,notice,reset,settings,setSettings}:{hosts:{id:string;name:string}[];notice:(s:string)=>void;reset:()=>void;settings:AgencySettings;setSettings:(s:AgencySettings)=>void}) {const[tab,setTab]=useState("Общие");const {limit,paused,tz,days}=settings;const setLimit=(limit:string)=>setSettings({...settings,limit:String(Math.max(1,Math.min(20,Number(limit)||1)))});const setPaused=(paused:boolean)=>setSettings({...settings,paused});const setTz=(tz:string)=>setSettings({...settings,tz});const setDays=(days:string)=>setSettings({...settings,days:String(Math.max(1,Math.min(365,Number(days)||1)))});return <div className="space-y-5"><PageHead title="Настройки" description="Общие ограничения, машины, подключения и восстановление.">{(tab==="Общие"||tab==="Хранение")&&<Button onClick={()=>notice("Общие настройки изменены только в макете.")}>Сохранить пример</Button>}</PageHead><TabBar value={tab} onChange={setTab} tabs={["Общие","Машины","Подключения","Хранение","Диагностика"]}/><div className="max-w-3xl space-y-4">{tab==="Общие"&&<Panel title="Работа агентства"><div className="space-y-4"><TextField label="Общий лимит параллельных задач" type="number" value={limit} onChange={setLimit}/><Field label="Часовой пояс агентства"><Choice label="Часовой пояс агентства" value={tz} onChange={setTz} options={["Europe/Madrid","Europe/Moscow","UTC"]}/></Field><div className="flex items-center justify-between"><span className="text-sm">Приостановить новые назначения</span><Switch aria-label="Приостановить назначения" checked={paused} onCheckedChange={setPaused}/></div></div></Panel>}{tab==="Машины"&&<MachinesPage/>}{tab==="Подключения"&&<TelegramSettings/>}{tab==="Хранение"&&<Panel title="История и резервирование"><TextField label="Срок хранения подробных журналов, дней" type="number" value={days} onChange={setDays}/><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" onClick={()=>notice("Экспорт будет включать профили и правила без секретов. В прототипе файл не создаётся.")}>Экспорт конфигурации</Button><Button variant="outline" onClick={()=>notice("Импорт будет показывать изменения до применения; автоматизации выключены по умолчанию.")}>Импорт конфигурации</Button></div></Panel>}{tab==="Диагностика"&&<Panel title="Режим прототипа"><Rows rows={[["Данные интерфейса","Демонстрационные, в памяти страницы"],["Выбор CLI и модели","Штатный каталог BB"],["Исполнение","Недоступно"],["События и cron","Только предпросмотр"]]}/><Button variant="outline" onClick={reset}>Сбросить пример</Button></Panel>}</div></div>;}
