import type { Automation, WebhookDraft } from "./data";
import { Button, TextField, Field, Choice, Panel } from "./shared";
import { useEffect, useState } from "react";
import { tr } from "../i18n";
const defaults:WebhookDraft={source:"Контентный workflow",topic:"research.delivered",auth:"hmac",mode:"observe",status:"ready",overlap:"queue"};
export function WebhookEditor({item,update}:{item:Automation;update:(a:Automation)=>void}) {
 const config={...defaults,...item.webhook};
 const change=(patch:Partial<WebhookDraft>)=>update({...item,webhook:{...config,...patch}});
 const [sample,setSample]=useState(JSON.stringify({schemaVersion:1,eventId:"example-001",topic:"research.delivered",occurredAt:"2026-09-13T18:00:00Z",subject:{externalId:"research-42",version:"1"},data:{status:"ready",reference:"artifact:research-42"}},null,2));
 const [verdict,setVerdict]=useState("");
 useEffect(()=>setVerdict(""),[item]);
 const preview=()=>{try{const body=JSON.parse(sample);if(body.schemaVersion!==1||typeof body.eventId!=="string"||!body.eventId.trim()||typeof body.topic!=="string"||typeof body.subject?.externalId!=="string")throw new Error(tr("Нужны schemaVersion: 1, eventId, topic и subject.externalId."));if(body.topic!==config.topic||config.status&&body.data?.status!==config.status){setVerdict(tr("Условия не совпали. Событие осталось бы в журнале без действия."));return;}setVerdict(config.mode==="off"?tr("Источник выключен: новые события не принимаются."):config.mode==="observe"?tr("Условия совпали. Режим наблюдения: только запись в журнал."):config.mode==="approval"?tr("Условия совпали. Во «Входящих» появилось бы согласование для отдела «{department}».",{department:item.department}):tr("Условия совпали. В проекте «{project}» создалась бы задача отделу «{department}» по шаблону из вкладки «Действие».",{project:item.project,department:item.department}));}catch(error){setVerdict(tr("Проверьте пример: {message}",{message:error instanceof Error?error.message:tr("неверный JSON")}));}};
 return <div className="space-y-5">
  <Panel title="Источник уведомлений"><div className="grid gap-4 md:grid-cols-2"><TextField label="Название источника" value={config.source} onChange={source=>change({source})}/><Field label="Режим работы"><Choice label="Режим вебхука" value={config.mode} onChange={mode=>change({mode})} options={[{value:"off",label:"Выключен"},{value:"observe",label:"Только наблюдать"},{value:"approval",label:"Запрашивать подтверждение"},{value:"auto",label:"Автоматически"}]}/></Field></div><p className="mt-3 text-xs text-muted-foreground">{tr("Привязан к проекту «{project}». Адресат и поручение задаются во вкладке «Действие».",{project:item.project})}</p></Panel>
  <Panel title="Подключение"><Field label="Планируемый адрес"><code className="block break-all rounded-md border border-border bg-muted/40 p-3 text-xs">POST /api/v1/plugins/agency/http/notify</code></Field><div className="mt-4"><Field label="Проверка отправителя"><Choice label="Авторизация вебхука" value={config.auth} onChange={auth=>change({auth})} options={[{value:"hmac",label:"Подпись HMAC-SHA256 и время отправки"},{value:"token",label:"Отдельный токен источника"}]}/></Field></div><p className="mt-3 text-sm text-muted-foreground">{tr("Адрес ещё не включён. Секрет создаётся на сервере при подключении источника; в агентский контекст он не попадёт.")}</p></Panel>
  <Panel title="Условия срабатывания"><div className="grid gap-4 md:grid-cols-2"><TextField label="Событие отправителя (topic)" value={config.topic} onChange={topic=>change({topic})}/><TextField label="Статус материала равен (data.status)" value={config.status} onChange={status=>change({status})}/></div><p className="mt-3 text-xs text-muted-foreground">{tr("Оба условия должны совпасть. Пустое поле статуса отключает только проверку статуса. Дубликаты одного eventId не создают повторную задачу.")}</p></Panel>
  <Panel title="Если работа уже идёт"><Choice label="Повторное событие по материалу" value={config.overlap} onChange={overlap=>change({overlap})} options={[{value:"queue",label:"Сохранить в очереди до завершения"},{value:"skip",label:"Пропустить с записью причины"},{value:"latest",label:"Оставить последнее ожидающее событие"}]}/><p className="mt-3 text-xs text-muted-foreground">{tr("События сопоставляются по источнику и subject.externalId. Работающий агент не прерывается новым уведомлением.")}</p></Panel>
  <Panel title="Проверка на примере"><TextField label="Пример тела уведомления (JSON)" multiline value={sample} onChange={value=>{setSample(value);setVerdict("");}}/><Button className="mt-3" variant="outline" onClick={preview}>{tr("Проверить условия")}</Button>{verdict&&<p role="status" className="mt-3 rounded-md bg-muted/50 p-3 text-sm">{verdict}</p>}<p className="mt-3 text-xs text-muted-foreground">{tr("Локальная проверка полей и маршрута. Подпись, доступность сервера, повторы и запуск здесь не проверяются. Запрос не отправляется.")}</p></Panel>
 </div>;
}
