export {
  STALE_BATCH_SIZE,
  STALE_ORIGIN_HOUR_MS,
  STALE_SWEEP_INTERVAL_MS,
  escalateStale,
  formatStaleBatchText,
  hasLiveAttempt,
  hasOpenDependency,
  hasOpenNeedsInputWait,
  isInLaunchQueue,
  isRunWatchOwnedStatus,
  isStaleCandidate,
  liveAttemptIsWatched,
  liveAttemptThreadId,
  lastMovementAt,
  parentBlocksSweep,
  recoverStaleNudges,
  stateSinceOf,
  sweepStaleJobs,
  sweepStaleNudges,
  flushStaleNudges,
  type StaleCandidateOpts,
  type StaleNudgeRow,
  type StaleRules,
  type StaleSweepPorts,
  type StaleSweepStats,
} from "./service.js";
