import { fail, ok, type DomainResult } from "../../../domain";
import { catalogSkillIdSchema, type CatalogSkillId } from "../../../shared/contracts/ids.js";
import { canonicalizeJson, sha256Hex } from "../context-snapshot/canonical.js";
import type { CatalogSkillEntry } from "../context-snapshot/types.js";
import type { LiveCatalogSkill, SkillCatalogPort } from "./ports.js";

const SKILL_ENTRY = "SKILL.md";

/**
 * Generated bytecode is not skill source. Excluded from inventory and hash:
 * any `__pycache__/` segment, and `*.pyc` / `*.pyo` (any directory).
 * `.py` sources, references, assets, README stay in the package.
 */
export function isGeneratedBytecodePath(path: string): boolean {
  const posix = path.replaceAll("\\", "/");
  const parts = posix.split("/");
  if (parts.includes("__pycache__")) return true;
  const base = parts.at(-1) ?? "";
  return /\.(pyc|pyo)$/i.test(base);
}

export function normalizeSkillPackagePath(path: string): string {
  return path.replaceAll("\\", "/").replace(/^\.\//, "");
}

function isSafeRelative(path: string): boolean {
  const posix = normalizeSkillPackagePath(path);
  if (!posix || posix.startsWith("/") || posix.includes("\0")) return false;
  const parts = posix.split("/");
  return parts.every((part) => part !== "" && part !== "." && part !== "..");
}

/** Deterministic inventory: SKILL.md ∪ listed files, minus generated bytecode. */
export function canonicalSkillPackageInventory(listed: readonly string[]): string[] {
  const inventory = new Set<string>([SKILL_ENTRY]);
  for (const raw of listed) {
    const path = normalizeSkillPackagePath(raw);
    if (!isSafeRelative(path) || isGeneratedBytecodePath(path)) continue;
    inventory.add(path);
  }
  return [...inventory].sort((left, right) => left.localeCompare(right));
}

/** Markdown links only. Inline examples, backticks, and placeholders are not package refs. */
export function referencedSkillPaths(skillMd: string): string[] {
  const found = new Set<string>();
  const link = /\]\(([^)]+)\)/g;
  let match: RegExpExecArray | null;
  while ((match = link.exec(skillMd))) {
    const raw = match[1].split("#")[0]?.trim() ?? "";
    if (!raw || raw.startsWith("http://") || raw.startsWith("https://")) continue;
    if (isSafeRelative(raw)) found.add(raw);
  }
  return [...found].sort();
}

export function skillPackageHash(files: readonly { path: string; content: string }[]): string {
  const body = files
    .map((file) => ({ path: file.path, sha256: sha256Hex(file.content) }))
    .sort((a, b) => a.path.localeCompare(b.path));
  return sha256Hex(canonicalizeJson(body));
}

export async function hashCatalogSkillPackage(
  catalog: SkillCatalogPort,
  listed: LiveCatalogSkill,
): Promise<DomainResult<CatalogSkillEntry>> {
  const idParsed = catalogSkillIdSchema.safeParse(listed.id);
  if (!idParsed.success) {
    return fail("invalid_catalog_skill_id", `catalog skill id is not skill_+64hex: ${listed.id}`);
  }
  if (listed.id.startsWith("skl_")) {
    return fail("invalid_catalog_skill_id", "Agency skl_* ids are not catalog skill ids");
  }
  const listedFiles = await catalog.listFiles(listed.id);
  if (!listedFiles.ok) return listedFiles;
  const skillMd = await catalog.getContent(listed.id, SKILL_ENTRY);
  if (!skillMd.ok) {
    return fail("skill_package_incomplete", `skill ${listed.id} is missing ${SKILL_ENTRY}`);
  }
  for (const raw of listedFiles.value) {
    const path = normalizeSkillPackagePath(raw);
    if (isGeneratedBytecodePath(path)) continue;
    if (!isSafeRelative(path)) {
      return fail("skill_package_incomplete", `skill ${listed.id} has unsafe package path ${path}`);
    }
  }
  const inventory = canonicalSkillPackageInventory(listedFiles.value);
  for (const ref of referencedSkillPaths(skillMd.value)) {
    if (!inventory.includes(ref)) {
      return fail(
        "skill_package_incomplete",
        `skill ${listed.id} markdown reference ${ref} is not in canonical package inventory`,
      );
    }
  }
  const files: { path: string; content: string }[] = [];
  for (const path of inventory) {
    const content = await catalog.getContent(listed.id, path);
    if (!content.ok) {
      return fail(
        "skill_package_incomplete",
        `skill ${listed.id} listed file ${path} is missing; package hash is listFiles inventory, not invented placeholders`,
      );
    }
    files.push({ path, content: content.value });
  }
  return ok({
    id: listed.id as CatalogSkillId,
    hash: skillPackageHash(files),
    source: listed.source,
    name: listed.name,
  });
}
